### ISSUE TITLE
Scheduled adjacent recordings cause 2nd recording to fail

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#104]
This happened on a 1.4.x CA. If you somehow have exactly adjacent recordings scheduled, the second recording fails to start.

In this case we had a recording scheduled for 1 hour (60min) from 10am - 11am, and another recording starting at 11am.

galicaster      2014-07-22 09:59:59,017 INFO    recorderui      Scheduled Start
galicaster      2014-07-22 09:59:59,020 ERROR   conf    Forcing default profile since current doesn't exits
galicaster      2014-07-22 09:59:59,020 INFO    recorderui      Recording
galicaster      2014-07-22 10:59:59,018 INFO    recorderui      Scheduled Stop
galicaster      2014-07-22 10:59:59,018 DEBUG   recorder        Stopping Recording and Restarting Preview
galicaster      2014-07-22 10:59:59,528 INFO    recorderui      Scheduled Start
galicaster      2014-07-22 10:59:59,531 ERROR   conf    Forcing default profile since current doesn't exits
galicaster      2014-07-22 10:59:59,556 INFO    recorder        eos
galicaster      2014-07-22 11:00:00,141 DEBUG   recorder        EMITTING restart preview
galicaster      2014-07-22 11:00:00,141 INFO    recorderui      Restarting Preview
galicaster      2014-07-22 11:00:00,144 INFO    worker  Creating Ingest Job for MP 25299576
galicaster      2014-07-22 11:00:00,146 INFO    worker  Executing Ingest for MP 25299576
galicaster      2014-07-22 11:00:00,154 INFO    worker  Zipping MP 25299576
galicaster      2014-07-22 11:00:00,154 DEBUG   serializer      Using System Zip
galicaster      2014-07-22 11:00:00,155 ERROR   conf    Forcing default profile since current doesn't exits
galicaster      2014-07-22 11:00:00,157 INFO    recorderui      Setting Devices the new way
galicaster      2014-07-22 11:00:00,158 DEBUG   recorder        Init bin Presenter galicaster.recorder.bins.rtp
galicaster      2014-07-22 11:00:00,167 DEBUG   recorder        Init bin audio galicaster.recorder.bins.pulse
galicaster      2014-07-22 11:00:00,171 DEBUG   recorder        Init bin presentation galicaster.recorder.bins.blackmagic
galicaster      2014-07-22 11:00:00,187 DEBUG   recorder        recorder preview
galicaster      2014-07-22 11:00:00,749 DEBUG   recorder        on sync message 'prepare-xwindow-id' 'presentation'
galicaster      2014-07-22 11:00:03,019 DEBUG   recorder        on sync message 'prepare-xwindow-id' 'Presenter'
galicaster      2014-07-22 11:00:18,342 DEBUG   mhhttpclient    Looking up Matterhorn endpoint for org.opencastproject.ingest
galicaster      2014-07-22 11:00:20,809 INFO    mhhttpclient    Ingesting to Server http://srvslsopc201.uct.ac.za:8080
galicaster      2014-07-22 11:02:38,359 INFO    worker  Finalized Ingest for MP 25299576

**Comment by silviabf** [comment]
I tried to reproduce this issue with galicaster 2.0. I schedule a recording from 10:00 to 11:00 and the next recording from 11:01 to 12:01, both recordings with ingest immediately. The two recordings are ok. I can not reproduce this issue then I will close it. If it happens again we will reopen the issue.
