### ISSUE TITLE
Don't log call errors for 204 response codes

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#105]
In utils/mhttpclient.py, an error is logged if a request gets a response code that is not 200:

 if status_code != 200:
            if self.logger:
                self.logger.error('call error in %s, status code {%r}: %s',
                                  urlparse.urlunparse(url), status_code, b.getvalue())
            raise IOError, 'Error in Matterhorn client'

However the GC dashboard returns status code 204, and as the docs/scripts/run_dashboard_push.py uses mhttpclient, GC logs are filled up with:

galicaster      2014-07-23 10:53:31,707 ERROR   mhhttpclient    call error in http://media.uct.ac.za/dashboard/rest/agents/jamesc/snapshot.png, status code {204}:

As 204 is not an error code, mhttpclient should not log an error when receiving it.

**Comment by hcaloto** [comment]
Thank you Stephen
