### ISSUE TITLE
Add CA name and version prominently to Recording page

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#106]
It would be nice to have the CA name and Galicaster version displayed prominently on the Recording page (e.g. top left or top right). The CA name is available under Status but not the version.

**Comment by hcaloto** [comment]
Fixing this requires tweaking the UI. We'll keep it in mind for future releases.

**Comment by silviabf** [comment]
This feature is improved to galicaster 2-beta2. As you can see in the attached picture, the CA name and the version is shown in the bottom left.

![beta2](https://cloud.githubusercontent.com/assets/11191010/15927969/b5b7d0c6-2e44-11e6-864c-05f42dbbb2c1.png)

I close this issue
