### ISSUE TITLE
Recording "started at" time is misleading

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#110]
When creating a recording from the Galicaster UI (click on Record button) rather than via scheduler, the mediapackage title is "Recording started at ..." but the date/time there is misleading.

It appears to be the date/time that Galicaster was started or entered preview, rather than the time that the recording actually started.

**Comment by hcaloto** [comment]
Thank you!

**Comment by smarquard** [comment]
The commit above causes a regression where the title of a scheduled recording is replaced by "Recording started at ..."

**Comment by hcaloto** [comment]
Thank you Stephen, I realized that this change should be done only for scheduled recordings

**Comment by smarquard** [comment]
The other way around - only for manual recordings. I fixed it in our fork with this commit:

https://bitbucket.org/cilt/galicaster-1.4/commits/e8b62ad56835a58433f887ed146414ebef7860a7
