### ISSUE TITLE
Run cleanstale job on init as well as overnight

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#111]
We are looking at power management options for our CAs where they will not necessarily be running overnight, e.g. they would come up when necessary for recordings and shut down later.

We would like the cleanstale job to also be executed on galicaster startup, so a CA will always execute this regardless of whether it's running overnight or not.

galicaster/plugins/cleanstale.py:

def init():
    conf = context.get_conf()
    dispatcher = context.get_dispatcher()
    dispatcher.connect('galicaster-notify-nightly', clear_job)
    dispatcher.connect('galicaster-init', clear_job)

**Comment by hcaloto** [comment]
Thanks, now you can set it using the config file:

[cleanstale]
checkoninit = true
