### ISSUE TITLE
Cannot set up the audio rate or container in the Pulse plugin

### ISSUE THREAD

**Issue by sinhote** [teltek/Galicaster#113]
The pulse bin implementation in the latest stable version lacks a way to set the audio rate or the audio container. 

The second problem comes from the fact that the default audio format (mp3) does not require a container on its own, but another formats (such as ogg or aac) do need one. I *think* one can use a construct like:
```
audioencoder = faac bitrate=160000 ! mp4mux
```
but this is clearly a misuse of the parameter, since we are not only including the encoder, but also the multiplexer. 

On the other hand, the audio rate must be set via a caps filter before or after the encoder, but the pipeline doesn't have one.

**Comment by hcaloto** [comment]
Thanks Ruben!
