### ISSUE TITLE
Default audio delay is 1s but should be 0s

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#129]
The default value for the delay parameter in the pulse bin is 1s, which also applies if you leave this out.

This is unexpected - if you don't specify a delay, it should not apply (i.e. default of 0s).

galicaster/recorder/bins/pulse.py:

 "delay": {
            "type": "float",
            "default": 1.0,
            "range": (0,10),
            "description": "Audio delay",
            },

**Comment by hcaloto** [comment]
I've checked that this parameter is not used in the release 1.4.2 since this version does not include the delay option. I've made a commit in order to fix it in the master branch.

Thank you Stephen
