### ISSUE TITLE
It doesn't catch a KeyboardInterrupt exception (Galicaster doesn't close)

### ISSUE THREAD

**Issue by hcaloto** [teltek/Galicaster#133]
Traceback (most recent call last):
  File "/home/hcaloto/workspace/Galicaster/galicaster/utils/gstreamer.py", line 26, in **call**
    def **call**(self, *args):
KeyboardInterrupt

**Comment by Alfro** [comment]
Fixed on: https://github.com/teltek/Galicaster/commit/a4c39d5f8183a9b5804021b41d276412e1a3e5a7

**Comment by silviabf** [comment]
Galicaster closes now correctly when you use Ctrl+C in the terminal. i close this issue.
