### ISSUE TITLE
problem when defining multiple tab widgets in the same view

### ISSUE THREAD

**Issue by abraiante** [teltek/Galicaster#136]
This is the output when launching Galicaster

> (run_galicaster.py:17249): Gtk-WARNING **: Overriding tab label for notebook
> 
> (run_galicaster.py:17249): Gtk-WARNING **: Overriding tab label for notebook

It can be solved creating a new glade file and removing the GtkNotebook widget that isn't being used.

**Comment by rubenrua** [comment]
More info in https://mail.gnome.org/archives/commits-list/2011-April/msg10925.html
