### ISSUE TITLE
Vumeter too thin and unaligned.

### ISSUE THREAD

**Issue by maruiz93** [teltek/Galicaster#137]
The vumeter in Galicaster1 is shorter and thicker than the one in GTK3.
![vumeter_gtk2](https://cloud.githubusercontent.com/assets/15313663/14491577/f4b133be-0179-11e6-8090-a8c523e8eaae.png)
![vumeter_gtk3](https://cloud.githubusercontent.com/assets/15313663/14491576/f4b1016e-0179-11e6-971d-d594513429e4.png)

**Comment by rubenrua** [comment]
The `Vumeter` widget is descendant of `GtkTable`.  `GtkTable` has been deprecated since version 3.4 and should not be used. Use `GtkGrid` instead of.

**Comment by bleedinge** [comment]
Fixed in #197, #201, #208
