### ISSUE TITLE
galicaster 2.x preview screen black after recording

### ISSUE THREAD

**Issue by flyapen** [teltek/Galicaster#184]
When performing a recording with galicaster 2.x alpha ( datapath capture card ) and stopping the recording the screen for both video previews goes black. If you exit the recorder view and re-enter the screen is back to normal.

The audio signal continues ( VU-meter ).

**Comment by hcaloto** [comment]
Thank you Kristof, let's give it a look

**Comment by flyapen** [comment]
I've updated to the latest alpha, this problem still occurs but in addition the video screen in the mediamanager when playing a recording is now black as well. The video files itself are correct when played via VLC or similar. Should I create a new issue for this?

**Comment by flyapen** [comment]
Just updated to beta1 and black screens in mediamanager are solved, in recorder there are still some issues. Sometimes both screens remain black, sometimes only one screen or both screens are ok.

**Comment by devangovender** [comment]
We're experiencing the same issue... screens sometimes work but in most instances remain black.

**Comment by bleedinge** [comment]
This has happened to us a few times, but never with the frequency you mention here @devangovender. 

We hope that the QA will produce some cases where this can be reproduced in our lab so we are able to fix it.

As soon as we have news we will update the issue.

**Comment by silviabf** [comment]
I have reproduced this issue. With the attached profile, after i stop the recording, the presentation preview is a black screen (the recording is ok).

Steps:
- Launch galicaster
- Select this profile
- Do a short recording (5 s.)
[webcam.ini.txt](https://github.com/teltek/Galicaster/files/299957/webcam.ini.txt)

**Comment by silviabf** [comment]
I have reproduced again this issue, with the blackmagic. With the attached profile, the preview of the blackmagic goes to black when i click on stop recording or in change preview order. The datapath preview works ok in this case

[blackmagic.ini.txt](https://github.com/teltek/Galicaster/files/303048/blackmagic.ini.txt)

**Comment by bleedinge** [comment]
We have commited several changes to the code to fix this and from our tests we have been unable to replicate it.

I'm closing this, but if possible, please test the 2.0.x branch and feel free to open the issue again if you can replicate the problem.
