### ISSUE TITLE
Error opening Galicaster

### ISSUE THREAD

**Issue by maruiz93** [teltek/Galicaster#200]
Sometimes, an error occur while opening Galicaster:
```

[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)
```

**Comment by hcaloto** [comment]
This issue should be fixed with:

https://github.com/teltek/Galicaster/commit/f77a2d885808715c9d4f5d40956eea3700f25fcc
https://github.com/teltek/Galicaster/commit/776ac1fbc87ce4e34b2653e35c4a0a21840af637

**Comment by silviabf** [comment]
This bug is solved in version beta2. There is no error when launch galicaster now. I close this issue
