### ISSUE TITLE
Merge in QR code plugin from UoM

### ISSUE THREAD

**Issue by androidwiltron** [teltek/Galicaster#219]
Hey!
great to see Galicaster community in full development swing again!
so I'd like to take up the offer of help to get manchester's QR code - code into Galicaster 2.0.
obviously this may be difficult but in 1.4 the issue was really boiled down to a couple of lines of code in the recorderui, the rest just slotted in.
here is the 1.4 patch:
[https://gist.github.com/androidwiltron/92691ab9680982a9bc62](url)
lines 86 - 94 was the hard part i chose to bring back how it was done in 1.3 to get QR code working.

here is the branch from UoM fork
https://github.com/UoM-Podcast/Galicaster/tree/f/qrcode1.4.2

**Comment by bleedinge** [comment]
Hi Andy,

It is great to hear that you want to merge this feature in Galicaster 2.0 We will have a look to the code and get back to you on it.

**Comment by hcaloto** [comment]
Hi!

We have done some improvements to the core in order to add the needed signals and methods for this development. It's already merged in the 2.0.x branch, so you can take a look at it and if you feel lack of something, please let us know.

I think that now it should be straightforward to create a pull request for the feature. You just need to adapt the plugin to GStreamer 1.x and use the signals we have just created.

https://github.com/teltek/Galicaster/pull/229

**Comment by androidwiltron** [comment]
That's great! I'm at apereo conference but once I'm back I'm going to put
some time into testing new GC.

Thanks again
Andy

**Comment by androidwiltron** [comment]
Hey again,
I've been working on this and with the changes you made to GC its really simplified some of the plugin stuff, thanks!
I'm close to a pull request, if you can its worth testing if this works for you.
this is the branch i'm working on
https://github.com/UoM-Podcast/Galicaster/tree/dev_plugin_qrcode

just some comments. i needed to add a function in the 'recorder' to get the private var `self.__start_record_time` so i could get the pipeline start time of the recording. is this OK?
i found i needed to get the bins / pipeline by again accessing the 'recorder' through the 'recorder service' is this the correct strategy? `pipeline = self.recorder.recorder.pipeline`

I'm wondering if these things should ave proxy functions in the 'service' to make it easier to write plugins. I really like the 'service' idea, makes it more like an API rather than trawling though the code looking for a hook.

nice work

thanks again
-andy

**Comment by Alfro** [comment]
The `self.__start_record_time` function was added to the recorder with no further issues.
Also, after the PR #434 the Manchester QR plugin for Galicaster has a project of its own instead: https://github.com/teltek/Galicaster-plugin-qrcode

I think this issue can be safely closed now. :)
