### ISSUE TITLE
Problem when a scheduled recording starts while a manual one is being done.

### ISSUE THREAD

**Issue by maruiz93** [teltek/Galicaster#221]
In this case, the scheduled recording does not start.

**Comment by androidwiltron** [comment]
just a suggestion. 
If possible, this should be configurable for different use cases. for example:

if recording, stop recording and start new one

or 

if recording, do not stop and just carry on

and

priority scheduled

or 

priority manual

**Comment by maruiz93** [comment]
Actually, it is configurable with the parameter overlap of the section allows.
It is false by default so there was really no error.
