### ISSUE TITLE
GUI: Mediapackage info window has menu bar 

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#244]
Steps:
- Launch galicaster
- Go to mediamanager
- Right click button in any recording
- Go to info

Problem: As you can see in the attached picture, the info window has a menu bar
![mediapackage_info](https://cloud.githubusercontent.com/assets/11191010/15748782/6ede67be-28e0-11e6-8633-cc138c4ff8d7.png)

**Comment by silviabf** [comment]
There is no menu bar in the info window in the beta 2 version, but, as it is shown in the attached picture, the info about the operations is shown now with numbers instead of labels
![new info window](https://cloud.githubusercontent.com/assets/11191010/15928236/0e79fe72-2e46-11e6-825d-026e1953f007.png)

**Comment by maruiz93** [comment]
Fixed: https://github.com/teltek/Galicaster/commit/8128eb590c77b16e4b836567b5e996359f89114c

**Comment by silviabf** [comment]
The operations info is shown with labels now. I close this issue.
