### ISSUE TITLE
GUI: Operations window buttons does not resize correctly

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#247]
Steps:
- Go to mediamanager
- Select any recording and click on operations
- Click on ingest nightly
- Click again on operations

Problem: As you can see in the attached picture, the text of cancel ingest nightly is followed by : . Besides, the size of button ingest is not adapted to the button of cancel.

![operations](https://cloud.githubusercontent.com/assets/11191010/15772014/f9807cc0-296e-11e6-9e7d-0a4344c95287.png)

**Comment by fishfree** [comment]
When back to the recording interface from Operation interface, the area of Quit button disappears. My screen resolution is 1280*1024.

**Comment by maruiz93** [comment]
Could you specify exactly the steps you follow to reproduce the issue?

**Comment by maruiz93** [comment]
Solved in #277.

**Comment by silviabf** [comment]
The button is resized correctly now, but the text is not correct, you have Cancel Ingest Nightly: instead of Cancel Ingest Nightly.

**Comment by silviabf** [comment]
The text is correct now. I close this issue.
@fishfree the bug you reported is duplicated in this issue: #265, we continue there with it. Thank you!
