### ISSUE TITLE
GUI: Next recording window is too big when there are scheduled recordings

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#249]
Steps:
- Go to recorder
- Schedule a recording
- Click on Next recordings button

Problem: As you can see in the attached picture, the size of the window is too big, and it is impossible to use the Record Now button.

![next recording](https://cloud.githubusercontent.com/assets/11191010/15772948/7a5f04d8-2974-11e6-9b95-0ee63e920e0f.png)

**Comment by maruiz93** [comment]
Pull-request #267

**Comment by silviabf** [comment]
The size of the window is correct in version beta 2. I close this issue.
