### ISSUE TITLE
GUI: the icon is just an ugly question mark.

### ISSUE THREAD

**Issue by fishfree** [teltek/Galicaster#250]
When I lock Galicaster to the launchbar, the icon is just an ugly question mark.

**Comment by hcaloto** [comment]
https://github.com/teltek/Galicaster/commit/8a89c8dee366e12c86d2f662bfcfb45ea0e98ff6

**Comment by silviabf** [comment]
As you can see in the attached picture, the icon in the lauchbar in the beta 2 version is the icon of galicaster.
![icon](https://cloud.githubusercontent.com/assets/11191010/15928846/aaf5aa46-2e49-11e6-8456-49c83a9da036.png)

I close this issue. Thank you fishfree!.
