### ISSUE TITLE
GUI: In profile selector window, default profile appears with left-aligned when open the window

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#251]
Steps:
- Click on profile selector

Problem: As you can see, default profile appears left-aligned. When you pass the mouse over the text or click on the window, it changes to center align.

**Comment by hcaloto** [comment]
https://github.com/teltek/Galicaster/pull/348

**Comment by silviabf** [comment]
All the profiles are left-aligned now. I close this issue.
