### ISSUE TITLE
Galicaster does not store the last loaded profile, it always starts with the default one

### ISSUE THREAD

**Issue by hcaloto** [teltek/Galicaster#258]
- Open Galicaster
- Change the recording profile
- Close & open Galicaster

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/b834066918a93c8f01a44c891700ceda547290e5

**Comment by silviabf** [comment]
In the beta 2 version, galicaster is launched with the same profile that we had when we close it before.

I close this issue.
