### ISSUE TITLE
Problem with blackmagic mini recorder

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#260]
Steps:
- Turn on the computer
- Configure a profile with blackmagic mini recorder (i used the attached profile)

[blackmagic.ini.txt](https://github.com/teltek/Galicaster/files/303009/blackmagic.ini.txt)

- Launch galicaster and select the blackmagic profile

Problem: the preview of the blackmagic is black, and you does not have sound. If you execute the pipeline in a terminal: gst-launch-1.0 decklinkvideosrc connection=hdmi mode=1080i50 ! queue ! xvimagesink, then you could see the blackmagic input correctly. After execute this command, if you launch galicaster again, the blackmagic input works ok until you reboot the computer.
Driver version: 10.6.4a21

**Comment by silviabf** [comment]
I detail a bit more the bug. The problem is only with the profile of the first comment. If you use this profile after turn on the computer, there is no blackmagic input. The signal is recovered with gst-launch command or if you select the attached profile in this comment. If you select this profile after turn on the computer, there is no problem with the blackmagic signal.

[blackmagic_audio_linea.ini.txt](https://github.com/teltek/Galicaster/files/318176/blackmagic_audio_linea.ini.txt)

**Comment by hcaloto** [comment]
It's very curious, there may be a problem with the driver or the firmware. When the error is present, by running this pipeline you will recover the video preview:

`gst-launch-1.0 decklinkvideosrc connection=hdmi mode=720p60 ! queue ! fakesink`

Silvia, could you please test if this bug appears using the card Intensity Pro?

**Comment by hcaloto** [comment]
There is still an issue when trying to use an audio input that is not available (I mean when the Blackmagic card does not support this mode), in this case Galicaster gets frozen and the starting process lasts for 10 seconds. But this is another issue, this also happens with the RTP bin when the source is not available. @silviabf please check if this issue already exists and if not, please create it.

**Comment by silviabf** [comment]
I can not replicate this issue with Intensity Pro. I will test now the solution with the Mini Recorder and also report the problem with the audio input.

**Comment by silviabf** [comment]
The bug is solved for Mini Recorder card. I reported the other issue: #334. I close this issue.
