### ISSUE TITLE
Various segfault in preview

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#264]
I could not describe the exact steps because i does not doing nothing when it is happened. I did some recordings with the webcam profile, I went to the mediamanager and watch the recordings and then I leave alone the computer with the galicaster in preview. When I return in a few minutes I found the next segfault:

Info in terminal: 
/usr/bin/galicaster: line 1: 29499 Segmentation fault      (core dumped) python

Info in dmesg:
[mié jun  8 16:37:14 2016] queue121:src[5029]: segfault at 7f06f1ffbe28 ip 00007f0701d0516f sp 00007f06f1ffbdc0 error 6 in libv4l2.so.0.0.0[7f0701d01000+9000]

It happened two times, but I could not replicate it.

**Comment by silviabf** [comment]
Today i have another segfault in preview. I attached the kern.log info. In the console i have the next message: 
`(run_galicaster.py:30339): Gdk-WARNING **: run_galicaster.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
`

[kern.log.txt](https://github.com/teltek/Galicaster/files/313781/kern.log.txt)

It seems to be related with datapath. The driver version that i am using is 7.11.0.214

**Comment by hcaloto** [comment]
It seems like there is an issue with v4l2 devices, this is the error in my case (kern.log):

```
[jue jun 30 12:16:32 2016] ------------[ cut here ]------------
[jue jun 30 12:16:32 2016] WARNING: CPU: 0 PID: 22134 at /build/linux-oXTOqc/linux-4.4.0/drivers/media/v4l2-core/v4l2-ioctl.c:1272 v4l_enum_fmt+0xd86/0x10f0 [videodev]()
```

**Comment by hcaloto** [comment]
It should be solved with https://github.com/teltek/Galicaster/commit/089a3a4ca2ab1ceba5e2122280723a87bdc91dc0 and https://github.com/teltek/Galicaster/commit/85db8131fc7af5b004eafbd788269d0a75098f8c

**Comment by silviabf** [comment]
I continue having the warning:
`[mar ago  2 10:18:14 2016] WARNING: CPU: 1 PID: 25563 at /build/linux-dcxD3m/linux-4.4.0/drivers/media/v4l2-core/v4l2-ioctl.c:1272 v4l_enum_fmt+0xd86/0x10f0 [videodev]()
`
but I have not any of these segfault in quite time. I close this issue ( i reopen if they happen again)
