### ISSUE TITLE
GUI: Problems with differents resolutions

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#265]
Steps:
- Change the screen resolution
- Launch galicaster
- Navigate between differents screens of galicaster

Problem:
I found some problems with the next resolutions:
- 1280x1024: The galicaster image is bigger than the resolution (as you can see in the attached picture)
  ![1280x1024](https://cloud.githubusercontent.com/assets/11191010/15900629/78afe582-2da0-11e6-98d0-75b571c9c7a5.png)
- 1024x768: The recorder screen is bigger than the resolution (home and mediamanager screen are ok)
  ![1024x768](https://cloud.githubusercontent.com/assets/11191010/15900688/b86be96e-2da0-11e6-8f76-3e144fb54a9c.png)
- 800x600: It is the same problem than 1024x768, and also in all the screens the image of galicaster 2.0 has a green line out of the image
  ![800x600](https://cloud.githubusercontent.com/assets/11191010/15900780/f8eb7f4a-2da0-11e6-91c0-ff7de13a96d2.png)
- 1440x900: The same problem than 1280x1024

**Comment by maruiz93** [comment]
Except the error from 800x600 resolution in the recorder view, bug fixed in #274

**Comment by silviabf** [comment]
In the version beta2, it is solved for 1024x768 and 1440x900.
It still fails for 800x600 
And for 1280x1024, it is solved except in the mediamanager screen, where the image is cut in the right side, as you can see in the attached picture.
![1280x1024_beta2](https://cloud.githubusercontent.com/assets/11191010/15961443/0e577aea-2f05-11e6-8742-017652291420.png)

**Comment by maruiz93** [comment]
Pull-request with 800x600 problems solved: #290.
In my screen with 1280x1024 resolution, media manager screen looks good with margins at both sides.
Do you see the margins now too?

**Comment by silviabf** [comment]
It is ok for 800x600. In 1280x1024, the mediamanager is cut in the right side (in a 4:3 screen or in a 16:9 screen with black margins).

**Comment by dpeite** [comment]
I didn't see anything wrong in my screen with 1280x1024 resolution

**Comment by silviabf** [comment]
It works correctly in 1280x1024. I close this issue.
