### ISSUE TITLE
Player: problem when move the seekbar in a paused video

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#266]
Steps:
- Go to mediamanager
- Play any video
- Pause the player
- Move the seekbar of the video to other instant of time
- Without stopping the video returns to the mediamanager

Problem: The reproduction of the video begin in the new instant of time but the botton of pause is active and the play button is not active. When you exit from the player, the reproduction continues until the end of the video and you hear the audio in the mediamanager screen.

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/30bac3c7f228dc58188ed75ba6e60e86e7298471

**Comment by silviabf** [comment]
In the beta 2 version, when you move the seekbar, the button pause is deactivated, and the reproduction begins with the play button working correctly. The reproduction does not continue now when you leave the player. I close this issue.
