### ISSUE TITLE
GUI: text without translate in some parts of the GUI

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#270]
Steps:
- Launch galicaster in spanish: LANGUAGE='es_ES' galicaster

Problem:
Some of the text are shown in english:
- In the home page: Buttons: recorder, mediamanager and quit are in english
- In the recorder: Name of the tabs: events, recording and status, button edit, and buttons stop and cancel in the window of stop recording. In the status tab: storage space left, recording space, core connectivity and agent name
- In the mediamanager: buttons edit, operation and delete. In the window of delete, buttons of delete and cancel. In the window of operation, text of ingest and export
- In the player: title and presenter, and buttons of edit, operation and delete

**Comment by dpeite** [comment]
More info: http://askubuntu.com/questions/140552/how-to-make-glade-load-translations-from-opt

**Comment by silviabf** [comment]
It is all translated now. I close this issue.
