### ISSUE TITLE
Plugin operations: improve the buttons layout when hide some operation buttons

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#271]
Steps:
- configure plugin operations in the conf.ini

`[operations]`
`hide = ingest exporttozip sidebyside`
`hide_nightly =`

Problem: As you can see in the attached picture, the buttons have differents sizes. It is one example of configuration, but there is other configuration possibilities that can improve its appearance also.
![plugin operation](https://cloud.githubusercontent.com/assets/11191010/15927573/d2bf52c2-2e42-11e6-91a2-47442b082f5f.png)

**Comment by maruiz93** [comment]
Pull request: #276

**Comment by silviabf** [comment]
The first combination is resolved. The buttons have the same size now,
 but there are another combinations that can improve its layout, as you can see in the attached picture.
![operation2](https://cloud.githubusercontent.com/assets/11191010/16010418/66df1bae-3181-11e6-8966-5fb8b8076e9e.png)

**Comment by maruiz93** [comment]
Fixed in #328

**Comment by silviabf** [comment]
It looks better now, as you can see in the attached picture. I close this issue.
![operations3](https://cloud.githubusercontent.com/assets/11191010/16299332/0440881e-393a-11e6-9a71-8cd6c70836f8.png)
