### ISSUE TITLE
Problem when stop a recording with a rtp profile

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#279]
Steps:
- Launch a recording with the attached profile
- Stop it

Problem:
The recording does not stop correctly. In the log you can see:
`galicaster	2016-06-10 12:59:49,330	DEBUG	heartbeat	galicaster-notify-short in 10
galicaster	2016-06-10 12:59:56,367	ERROR	recorder	Timeout trying to receive EOS message
galicaster	2016-06-10 12:59:56,367	ERROR	service	Handle error (Timeout trying to receive EOS message)
`
the recording stops by time out, and it is not correctly closed.
[rtp.ini.txt](https://github.com/teltek/Galicaster/files/308870/rtp.ini.txt)

**Comment by hcaloto** [comment]
Related to #227

**Comment by silviabf** [comment]
Changing src0 by src_0 in the profile as it is said in issue #227, there is no error when you stop the recording. I close this issue.
