### ISSUE TITLE
Minimum audio threshold does not work

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#287]
Steps:
- Edit the conf.ini
- Change the minimum threshold to the audio to -30 dB

`[audio]`
`min = -30`
`keep_closed = False`
- Launch galicaster and go to recorder

Problem: the threshold for the no audio window is always -50 dB, the limit of the vu meter. It is not depends of the conf.ini

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/c3368c0d5ad7252a363f55fa5835ba29546459e9

**Comment by silviabf** [comment]
The minimum threshold is set now by the value of the conf.ini. I close this issue.
