### ISSUE TITLE
audio mimetype is not set correctly for flac audio

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#295]
This seems to be a regression as this was fixed in #78 for galicaster 1.x.

In galicaster 2.x, with an audio track like this which is recording in flac format:

[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_audio_CODEC-00.analog-mono
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.2

we get a manifest.xml like this with the wrong mimetype for audio:

      <track id="track-1" type="presenter/source">
         <tags>
            <tag>archive</tag>
         </tags>
         <mimetype>audio/mp3</mimetype>
         <url>audio.flac</url>
         <duration>59875</duration>
      </track>

**Comment by hcaloto** [comment]
Thank you Stephen, we are going to test it, but anyway this commit should solve it

**Comment by smarquard** [comment]
Thanks, I have confirmed that this fixes it (for the audio/flac case) on our test CA.

**Comment by silviabf** [comment]
The mimetype is correct now:
```
<track id="track-1" type="presenter/source">
         <tags>
            <tag>archive</tag>
         </tags>
         <mimetype>audio/flac</mimetype>
         <url>audio.flac</url>
         <duration>43403</duration>
      </track>
```
I close this issue. Thanks Stephen by the report.
