### ISSUE TITLE
Error after stop a long recording

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#296]
Steps:
- Schedule a recoding of 5:50 with the attached profile

Problem: After finished the recording, galicaster crash. In the console there is the next message:

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

In only in the log: apport.log.1 you can see another info about the error:

```
ERROR: apport (pid 24230) Tue Jun 14 01:50:03 2016: called for pid 14333, signal 6, core limit 0
ERROR: apport (pid 24230) Tue Jun 14 01:50:03 2016: executable: /usr/bin/python2.7 (command line "python ./run_galicaster.py")
ERROR: apport (pid 24230) Tue Jun 14 01:50:03 2016: debug: session gdbus call: (true,)

ERROR: apport (pid 24230) Tue Jun 14 01:50:03 2016: this executable already crashed 2 times, ignoring
```

The recording does not have any problem

**Comment by hcaloto** [comment]
It should be solved with https://github.com/teltek/Galicaster/commit/089a3a4ca2ab1ceba5e2122280723a87bdc91dc0 and https://github.com/teltek/Galicaster/commit/85db8131fc7af5b004eafbd788269d0a75098f8c

**Comment by silviabf** [comment]
This bug is fixed. I close this issue.
