### ISSUE TITLE
Plugin notifycrash does not work correctly

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#299]
Steps:
- Configure the plugin in the conf.ini
- Launch galicaster and do a recording
- Kill galicaster during the recording to simulate the crash
- Launch galicaster again

Problem: there is no mail with the crash. In the mediamanager you can see that the recording is recovered but in the log you can see:

`galicaster	2016-06-14 12:08:45,730	DEBUG	notifycrash	Nothing to do (does not exist '.recording_crash' file)`

The problem is that recording is now recovered by galicaster and the plugin does not find any recording in rectemp when galicaster is launched

**Comment by hcaloto** [comment]
This plugin is discontinued, since Galicaster saves the recording in the media manager. The plugin was useful when this feature didn't exist.
