### ISSUE TITLE
Plugin screensaver: error at start

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#304]
Steps:
- In the conf.ini, configure the plugin screensaver (with default values)
- Launch galicaster

Problem: In the log, you have the next error when the plugin start:
`galicaster	2016-06-14 18:13:02,117	ERROR	__init__	Error starting plugin screensaver: <dispatcher.Dispatcher object at 0x7fe0d102ee60 (galicaster+core+dispatcher+Dispatcher at 0x1cc2d00)>: unknown signal name: reload-profile
`

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/088ff2b5ee61f4447274c44d49f639df1c32b089

**Comment by silviabf** [comment]
The plugin screensaver starts correctly now. i close this issue.
