### ISSUE TITLE
Plugin forcedurationrec: the recordings stopped by timeout

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#307]
Steps:
- Configure the plugin forcedurationrec in the conf.ini to stop in one minute
- Launch galicaster and go to recorder
- Start a recording and wait a minute

Problem:
After one minute, the recording stops, but not correctly, it stops by time out. You can see in the log:
```
galicaster	2016-06-15 11:26:45,483	ERROR	recorder	Timeout trying to receive EOS message
galicaster	2016-06-15 11:26:45,483	ERROR	service	Handle error (Timeout trying to receive EOS message)
```

**Comment by hcaloto** [comment]
It should be solved with https://github.com/teltek/Galicaster/commit/089a3a4ca2ab1ceba5e2122280723a87bdc91dc0 and https://github.com/teltek/Galicaster/commit/85db8131fc7af5b004eafbd788269d0a75098f8c

**Comment by silviabf** [comment]
After more than 100 recordings with forcedurationrec, the issue is not replicate with the last version. I close this issue.
