### ISSUE TITLE
Plugin appearance: Error at start

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#308]
Steps:
- Configure the plugin appearance in the conf.ini
- Launch galicaster

Problem: the plugin does not start, this message is shown in the log:
```
galicaster	2016-06-15 12:47:11,416	ERROR	__init__	Error starting plugin appearence: No module named appearence
galicaster	2016-06-15 12:47:11,416	DEBUG	__init__	Plugin appeareance not enabled in conf

```

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/69397eced6f671d33d86a1676917131b2993ac60

**Comment by silviabf** [comment]
Plugin appearance works now. I close this issue
