### ISSUE TITLE
plugin screensaver: screensaver appears after 10 minutes when galicaster is recording

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#312]
Steps:
- configure the plugin screensaver in the conf.ini (with a time different of 10 minutes)
- Launch galicaster
- Launch a recording

Problem: After 10 minutes of recording, the screensaver appears. If you execute in a terminal: xset -q you can see:
```
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  600    cycle:  600
Colors:
  default colormap:  0x22    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
DPMS (Energy Star):
  Standby: 150    Suspend: 155    Off: 160
  DPMS is Enabled
  Monitor is On
```
There is another screensaver configure in 10 minutes that appears during the recording

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/pull/314/commits/94cb2d038b4a38f7a361fdc885f5afb05921b220

**Comment by silviabf** [comment]
It is solved now. I close this issue.
