### ISSUE TITLE
Plugin screensaver: screensaver dissapears when schedule a recording

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#315]
Steps:
- Configure screensaver plugin to 2 minutes in conf.ini
- Launch galicaster (leave events tab as default)
- Wait until screensaver appears
- Schedule a recording for within 10 minutes 

Problem:
The screensaver disappears when galicaster receives the scheduled recording, and it does not appears again (neither when the scheduled recording is over).

**Comment by hcaloto** [comment]
Fixed in https://github.com/teltek/Galicaster/commit/c02206783b156740e6927888a468f2ea2cb30478

**Comment by silviabf** [comment]
This bug is solved. The screensaver does not disappear until the scheduled recording starts. I close this issue.
