### ISSUE TITLE
Error in galicaster when the audio is the track 1 in a profile

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#317]
Steps:
- Use a profile with audio as track1 for example:
```
[data]
name = test

[track1]
name = audio
device = pulse
flavor = presenter
location = default
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.2

[track2]
name = presentation
device = v4l2
flavor = presenter
location = /dev/screen
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=30/1,width=1024,height=768
active = True
```
- Launch galicaster and select this profile

Problem: the 80% of the times the galicaster give a error in the log and it is not correctly launched. The error in the log is:
```
galicaster	2016-06-17 12:02:48,084	ERROR	galicaster_public/recorder/recorder	Timeout getting recorder status, current status: (<enum GST_STATE_CHANGE_ASYNC of type Gst.StateChangeReturn>, state=<enum GST_STATE_PAUSED of type Gst.State>, pending=<enum GST_STATE_PLAYING of type Gst.State>)
galicaster	2016-06-17 12:02:48,085	ERROR	galicaster_public/recorder/service	Handle error (Timeout getting recorder status, current status: (<enum GST_STATE_CHANGE_ASYNC of type Gst.StateChangeReturn>, state=<enum GST_STATE_PAUSED of type Gst.State>, pending=<enum GST_STATE_PLAYING of type Gst.State>))
```

**Comment by smarquard** [comment]
I can reproduce this on one of our test CAs. It also seems to result in preview screens showing black.

It seems to be related to the combination of audio track first and v4l2 / datapath device, as I did not see it when testing audio as the first track and rtp as the second track.

**Comment by hcaloto** [comment]
I've tried to solve it by using a workaround despite I know this is not the best solution. This commit makes sure the video tracks are always loaded before the audio ones. Maybe later we can try to find the best solution

**Comment by silviabf** [comment]
This bug is resolved, galicaster does not crash if audio is the first track. I close this issue.
