### ISSUE TITLE
Add audio delay feature back to 2.0.x

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#319]
It looks like the audio delay feature in the pulse bin is only in the master branch, and not in 1.4.x or 2.0.x:

https://github.com/teltek/Galicaster/blob/master/galicaster/recorder/bins/pulse.py

Please could this feature be added back to 2.0.x.

Commits:
https://github.com/teltek/Galicaster/commit/3f5884109f631a080c09a4b3dead74ec2e7da2e8#diff-0e67ca108eb71e7287aa728feb4651d4
https://github.com/teltek/Galicaster/commit/eab129633237ea8de9a355a1e5e05ab12ab99532#diff-0e67ca108eb71e7287aa728feb4651d4
https://github.com/teltek/Galicaster/commit/494f8687ae1c0300d4d4c9b0079c8a56f336f74a#diff-0e67ca108eb71e7287aa728feb4651d4

**Comment by hcaloto** [comment]
Hi @smarquard 

Did this feature work as expected in your case? We have had some issues when we mixed audio and video due to different timestamps of the packets.

Anyway, I'm going to bring this feature back to Galicaster.

**Comment by hcaloto** [comment]
I've just added this feature to Galicaster but there is a problem regarding to tracks duration. As far as I know the audio track lasts more than the others (and this is precisely the configured delay)

**Comment by smarquard** [comment]
It works if you trim the start of the video during the workflow. If you don't, the sync goes out by 1s or so. This is described here:

https://opencast.jira.com/browse/MH-11032

If you have another solution to this, we're open to looking at it, but currently the Galicaster change is the best known option.

**Comment by silviabf** [comment]
It is not working in the last version

**Comment by hcaloto** [comment]
Sorry, I forgot creating the pull request and merge it to 2.0.x

**Comment by silviabf** [comment]
This feature is been added to galicaster 2. I close this issue. Thanks @smarquard !
