### ISSUE TITLE
Console errors stopping a recording (datapath / v4l2)

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#320]
Galicaster 2.0.x, Ubuntu 16, Datapath E2S card

When a recording stops, the following errors are shown on the console:

** (run_galicaster.py:15226): CRITICAL **: gst_v4l2_buffer_pool_process: assertion 'gst_buffer_pool_is_active (bpool)' failed

** (run_galicaster.py:15226): CRITICAL **: gst_v4l2_buffer_pool_process: assertion 'gst_buffer_pool_is_active (bpool)' failed

The recording is successful.

profile is:

[track1]
name = presentation
device = v4l2
flavor = presenter
location = /dev/video0
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
active = True

[track2]
name = presentation2
device = v4l2
flavor = presentation
location = /dev/video1
file = presentation2.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
active = True

[track3]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
#delay = 0.2

**Comment by androidwiltron** [comment]
I can replicate this error with the above config.

**Comment by androidwiltron** [comment]
after testing on the newest 2.0.x, this bug looks to be resolved (or at least its not being written out to stout  haha)

**Comment by silviabf** [comment]
@smarquard we cannot replicate this bug with the last version of code. Can you replicate it in your CA or can we close it? Thanks in advance!

**Comment by smarquard** [comment]
Still shows up for us. It's associated with these errors in /var/log/syslog:

Jul 20 10:54:14 alex1b-ca kernel: [15841.172626] ------------[ cut here ]------------
Jul 20 10:54:14 alex1b-ca kernel: [15841.172629] WARNING: CPU: 3 PID: 6630 at /build/linux-BvkamA/linux-4.4.0/drivers/media/v4l2-core/v4l2-ioctl.c:1272 v4l_enum_fmt+0xd86/0x10f0 [videodev]()
Jul 20 10:54:14 alex1b-ca kernel: [15841.172629] Unknown pixelformat 0x20203859
Jul 20 10:54:14 alex1b-ca kernel: [15841.172630] Modules linked in: snd_usb_audio snd_usbmidi_lib mac_hid snd_hda_codec_hdmi rgb133(POE) snd_hda_codec_realtek intel_rapl x86_pkg_temp_thermal intel_powerclamp snd_hda_codec_generic coretemp snd_hda_intel videodev snd_hda_codec snd_hda_core snd_hwdep media kvm snd_pcm irqbypass crct10dif_pclmul crc32_pclmul snd_seq_midi snd_seq_midi_event snd_rawmidi aesni_intel snd_seq aes_x86_64 snd_seq_device snd_timer lrw snd gf128mul glue_helper soundcore ablk_helper cryptd mei_me mei serio_raw shpchp lpc_ich parport_pc ppdev lp parport autofs4 hid_generic usbhid hid i915 video i2c_algo_bit drm_kms_helper ahci syscopyarea libahci psmouse sysfillrect sysimgblt fb_sys_fops r8169 drm mii
Jul 20 10:54:14 alex1b-ca kernel: [15841.172643] CPU: 3 PID: 6630 Comm: gc-v4l2-src:src Tainted: P        W  OE   4.4.0-28-generic #47-Ubuntu
Jul 20 10:54:14 alex1b-ca kernel: [15841.172644] Hardware name: ASUS All Series/H87M-E, BIOS 0703 10/30/2013
Jul 20 10:54:14 alex1b-ca kernel: [15841.172644]  0000000000000286 000000006b8630bc ffff88009912bbf0 ffffffff813eb1a3
Jul 20 10:54:14 alex1b-ca kernel: [15841.172645]  ffff88009912bc38 ffffffffc0480a78 ffff88009912bc28 ffffffff81081102
Jul 20 10:54:14 alex1b-ca kernel: [15841.172646]  ffff88009912bda0 0000000000000000 0000000000000000 ffffc90000e31000
Jul 20 10:54:14 alex1b-ca kernel: [15841.172648] Call Trace:
Jul 20 10:54:14 alex1b-ca kernel: [15841.172649]  [<ffffffff813eb1a3>] dump_stack+0x63/0x90
Jul 20 10:54:14 alex1b-ca kernel: [15841.172650]  [<ffffffff81081102>] warn_slowpath_common+0x82/0xc0
Jul 20 10:54:14 alex1b-ca kernel: [15841.172651]  [<ffffffff8108119c>] warn_slowpath_fmt+0x5c/0x80
Jul 20 10:54:14 alex1b-ca kernel: [15841.172654]  [<ffffffffc046b6f6>] v4l_enum_fmt+0xd86/0x10f0 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172655]  [<ffffffff810b3bd5>] ? select_task_rq_fair+0x625/0x700
Jul 20 10:54:14 alex1b-ca kernel: [15841.172658]  [<ffffffffc046c2c1>] __video_do_ioctl+0x291/0x310 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172659]  [<ffffffff810ab0e4>] ? check_preempt_curr+0x54/0x90
Jul 20 10:54:14 alex1b-ca kernel: [15841.172662]  [<ffffffffc046bd96>] video_usercopy+0x336/0x5b0 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172664]  [<ffffffffc046c030>] ? video_ioctl2+0x20/0x20 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172666]  [<ffffffff811c002d>] ? handle_mm_fault+0xcdd/0x1820
Jul 20 10:54:14 alex1b-ca kernel: [15841.172669]  [<ffffffffc046c025>] video_ioctl2+0x15/0x20 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172671]  [<ffffffffc04676a3>] v4l2_ioctl+0xd3/0xe0 [videodev]
Jul 20 10:54:14 alex1b-ca kernel: [15841.172672]  [<ffffffff81220b6f>] do_vfs_ioctl+0x29f/0x490
Jul 20 10:54:14 alex1b-ca kernel: [15841.172673]  [<ffffffff8106b554>] ? __do_page_fault+0x1b4/0x400
Jul 20 10:54:14 alex1b-ca kernel: [15841.172674]  [<ffffffff81220dd9>] SyS_ioctl+0x79/0x90
Jul 20 10:54:14 alex1b-ca kernel: [15841.172675]  [<ffffffff818276b2>] entry_SYSCALL_64_fastpath+0x16/0x71
Jul 20 10:54:14 alex1b-ca kernel: [15841.172676] ---[ end trace a2d3c541aaedbfca ]---

**Comment by smarquard** [comment]
root@alex1b-ca:~# dmesg | grep -i datapath
[   12.742256] rgb133: rgb133_init: Datapath Ltd. - Vision Capture Driver ver 7.11.0.214 loaded ok.

root@alex1b-ca:~# uname -a
Linux alex1b-ca.uct.ac.za 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by smarquard** [comment]
Can't reproduce any longer. The "unknown pixelformat" in /var/log/syslog is normal logging for v4l2 and not an indication of an error, according to Datapath support.
