### ISSUE TITLE
Quit confirmation dialog produces console warning "GtkDialog mapped without a transient parent"

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#321]
When you click the Quit button in Galicaster 2.0.x, the "are you sure?" popup also produces this warning in the console:

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by hcaloto** [comment]
This warning appears for all popups except the metadata editor, we had to remove this property (transient_for) in order to be able to apply some cosmetic changes (such as shadow)

**Comment by hcaloto** [comment]
It seems like now we can add this property without losing cosmetic changes

**Comment by silviabf** [comment]
The message does not appears in the console now. I close this issue. Thanks @smarquard!
