### ISSUE TITLE
Add a variable to know the recording folder

### ISSUE THREAD

**Issue by miesgre** [teltek/Galicaster#33]
I am using a mp4mux as a muxer in Galicaster, but I want to pass the parameter 'moov-recovery-file'

Example:  mp4mux moov-recovery-file=${galicaster-working-folder}/file.mrf

But I Galicaster does not recognise ${galicaster-working-folder}.
¿Maybe you can add an aux.replace('${galicaster-working-folder}', self.options['path']) or something similar to the bins?

If I use a mp4mux, the moov file is written at the end of the file. If Galicaster breaks while is recording, I can not play the video recorded, so I need to create a moov recovery file in case Galicaster breaks.

**Comment by bleedinge** [comment]
Thanks for the comment.

We've finally closed this issue as Galicaster switches its working directory to the rectemp folder in the repository referenced in the config file.

Now you can write something like

> mpmux moov-recovery-file=recovery.mrf and it should get written to the rectemp folder, that indeed is a folder where current recording is being stored and Galicaster should have permissions to deal with the file properly.
