### ISSUE TITLE
If-modified-since / ETAG not working in GC 2.x

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#332]
Galicaster 2.x does not appear to be setting or checking the calendar requests properly to avoid a calendar update on every request.

Testing with an Opencast 2.x server, a GC 1.4.x CA gets 304 Not modified http responses for calendar updates (after the initial request), whereas a GC 2.x CA gets 200 OK responses with the full calendar on every request.

**Comment by smarquard** [comment]
Originally added in #64

**Comment by hcaloto** [comment]
Hi @smarquard, 

I'm testing it with Opencast 2.x from https://github.com/learnweb/docker-opencast and it works fine, I get:

```
hcaloto	2016-06-27 11:20:46,480	INFO	opencast/service	Proccess ical
hcaloto	2016-06-27 11:20:46,493	INFO	opencast/client	iCal Not modified
```

In my case, this is the status code and the Etag that Galicaster receives from Opencast:

```
# Galicaster init
200 mod1466692942018
304 mod1466692942018
304 mod1466692942018
304 mod1466692942018
304 mod1466692942018
304 mod1466692942018
# New event, so the status code should be 200, 304, 304, ...
200 mod1467019015114
200 mod1467019075116
200 mod1467019135110
304 mod1467019135110
304 mod1467019135110
304 mod1467019135110
```

As you can see there may be an issue in Opencast, since the Etag is not the same when the schedule don't change.

Regards

**Comment by bleedinge** [comment]
@smarquard 

What do you think? It looks like this isn't a Galicaster issue. Any thoughts?

**Comment by smarquard** [comment]
We're still seeing this, with our Opencast 1.4.x server as well. The GC 1.4.x CAs get 304s, the GC 2.x CAs always get 200 responses.

**Comment by smarquard** [comment]
Can't reproduce this any more.
