### ISSUE TITLE
Timeouts in conf-dist.ini are too short

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#333]
The timeout values added in #87 in conf-dist.ini are too short (GC 2.x)

If you create a large number of events in Opencast for a CA (e.g. > 1000), then the timeout of 2s is too short to receive the calendar update. Galicaster closes the connection before Opencast has finished writing the calendar. 

I'd suggest

connect_timeout = 30
timeout = 30

(it's probably timeout that is usually the issue here, not connect_timeout).

**Comment by silviabf** [comment]
The defaults timeous values in conf-dist.ini are set now to 30. I close this issue. Thanks @smarquard!
