### ISSUE TITLE
Recordings popup causes UI to become non-responsive with many scheduled recordings

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#335]
Schedule a large number of recordings for a CA (e.g. 1000+) or use the attached calendar file.

In GC 2.x, click on the gear icon in Events / Upcoming.

UI becomes non-responsive.
[calendar.ical.gz](https://github.com/teltek/Galicaster/files/329801/calendar.ical.gz)

**Comment by silviabf** [comment]
Galicaster only shows now the 5 firsts scheduled recordings in the Next Recording window, then Galicaster does not block with 1000 scheduled recordings. I close this issue. Thanks @smarquard!
