### ISSUE TITLE
Missing h.264 decoder after galicaster 2.x install

### ISSUE THREAD

**Issue by flyapen** [teltek/Galicaster#351]
Playback in mediamanager doesn't work after a fresh install of the latest galicaster package ( beta2 ). 
The error in the error log is 
`
galicaster      2016-07-08 10:54:40,576 ERROR   player/player   gstdecodebin2.c(4565): gst_decode_bin_expose (): /GstPipeline:galicaster_player/GstDecodeBin:decode-track-0:
no suitable plugins found:
Missing decoder: ITU H.264 (High 4:2:2 Profile) (video/x-h264, variant=(string)itu, framerate=(fraction)24/1, max-input-size=(int)149576, width=(int)1280, height=(int)720, pixel-aspect-ratio=(fraction)1/1, parsed=(boolean)true, stream-format=(string)avc, alignment=(string)au, profile=(string)high-4:2:2, level=(string)3.1, codec_data=(buffer)017a001fffe1001a677a001fbcd9405005bb011000000300100000030308f183196001000568eae13cb0)

galicaster      2016-07-08 10:54:42,043 ERROR   player/player   gstbaseparse.c(3578): gst_base_parse_loop (): /GstPipeline:galicaster_player/GstDecodeBin:decode-track-2/GstMpegAudioParse:mpegaudioparse10:
streaming stopped, reason not-linked
`

Manually installing gstreamer1.0-libav fixes this issue.

**Comment by bleedinge** [comment]
Thanks for reporting this.

It appears that there is a missing dependency in galicaster 2. We will be adding the gstreamer1.0-libav package as a dependency to the galicaster package as soon as possible.

Will close this ticket once it is done.

**Comment by hcaloto** [comment]
Thank you @flyapen, I've just added the dependency and also updated the DEB package, so the issue should not happen.

@silviabf, you are free to test this issue with a new installation (a clean one, I mean formatting the computer). Then check if you are able to playback any recordings and if the dependency is installed.

**Comment by steven09176** [comment]
Recording failed  when conf.ini set to rtp device , 
[track1]
name = AXIS9514
device = rtp
flavor = presenter
location = rtsp://x.x.x.x:554/axis-media/media.amp?videocodec=h264
file = CAMERA.avi
cameratype = h264
audio = False
muxer = avimux

**error report :**   gst-stream-error-quark: Internal data flow error. (1) (gstrtspsrc.c(5069): gst_rtspsrc_loop (): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+rtp+GCrtp:galicaster+recorder+bins+rtp+gcrtp1/GstBin:bin6/GstRTSPSrc:gc-rtp-src:
streaming task paused, reason not-negotiated (-4))

**Comment by hcaloto** [comment]
Hi @steven09176 and thank you for reporting.

In this case it seems like the right place for this comment should be the issue #95. As you can see in that issue, Galicaster is not compatible with RTP and avimux, maybe you should consider using another muxer like mp4mux or matroskamux.

Let's check if the dependency is already in the latest package. If you are interested on using avimux and RTP, please write a comment in #95

**Comment by steven09176** [comment]
Hi,
It worked by using matroskamux  and successfully ingested to opencast
Thanks

**Comment by silviabf** [comment]
Fixed. I close this issue. Thanks @flyapen !
