### ISSUE TITLE
Miss the profile.execute 

### ISSUE THREAD

**Issue by rubenrua** [teltek/Galicaster#354]
See configuration script  https://wiki.teltek.es/display/Galicaster/Input+Profiles

Connect to `action-reload-profile` signal in a profile service.

**Comment by rubenrua** [comment]
NOTE: The profile execution must be before mounting the pipeline.

**Comment by rubenrua** [comment]
we need a python lint.

**Comment by rubenrua** [comment]
We have a python lint: https://travis-ci.org/teltek/Galicaster/builds/147788882

And a lot of issues to fix.

**Comment by rubenrua** [comment]
Fixed in d382fcc. @silviabf check it again

**Comment by silviabf** [comment]
It is ok now. The script is executed every time the profile is loaded. I close this issue.
