### ISSUE TITLE
Use set_properties for atomic changes.

### ISSUE THREAD

**Issue by rubenrua** [teltek/Galicaster#364]
When muting inputs: https://github.com/teltek/Galicaster/blob/dev_mute_inputs/galicaster/recorder/bins/blackmagic.py#L295

use
```python
        src1 = self.get_by_name('gc-blackmagic-videobox')
        src1.set_properties(top=-10000, bottom=10000)
```

instead of

```python
        src1 = self.get_by_name('gc-blackmagic-videobox')
        src1.set_property('top', -10000)
        src1.set_property('bottom', 10000)
```

NOTE: [Documentation In `C`](https://developer.gnome.org/gobject/stable/gobject-properties.html#gobject-multi-properties)

**Comment by dpeite** [comment]
Fixed in 4b9020e
