### ISSUE TITLE
Problems with parameter channels with walues between 3 and 16

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#372]
Steps:
- Create a profile with channels parameter in audio (as the attached profile for example)
[webcam.ini.txt](https://github.com/teltek/Galicaster/files/388171/webcam.ini.txt)

- Change the value of channels between 3 and 16
- Restart galicaster after any change.

Problem: There is two incorrect behaviours depending of the value of channels:
- If channels is 3, 4, 6 or 8: In the recoder the VU meter shows stereo but galicaster records mono.
- If channels is 5,7,9,...,16: There is an error.
In the console you can see:
```
(run_galicaster.py:3910): GStreamer-CRITICAL **: _gst_util_uint64_scale: asserti
on 'denom != 0' failed

(run_galicaster.py:3910): GStreamer-CRITICAL **: gst_segment_to_running_time: as
sertion 'segment->format == format' failed

(run_galicaster.py:3910): GStreamer-CRITICAL **: gst_segment_to_stream_time: ass
ertion 'segment->format == format' failed
```
and in the galicaster log:
```
galicaster	2016-07-28 12:04:21,522	ERROR	recorder/recorder	Timeout 
getting recorder status, current status: (<enum GST_STATE_CHANGE_ASYNC of type G
st.StateChangeReturn>, state=<enum GST_STATE_PAUSED of type Gst.State>, pending=
<enum GST_STATE_PLAYING of type Gst.State>)
galicaster	2016-07-28 12:04:21,522	ERROR	recorder/service	Handle e
rror (Timeout getting recorder status, current status: (<enum GST_STATE_CHANGE_A
SYNC of type Gst.StateChangeReturn>, state=<enum GST_STATE_PAUSED of type Gst.St
ate>, pending=<enum GST_STATE_PLAYING of type Gst.State>))
galicaster	2016-07-28 12:04:31,523	DEBUG	recorder/recorder	Resume r
ecorder before stopping

```
Galicaster starts, but spends a lot of time to start and the profile has the preview in black.

**Comment by hcaloto** [comment]
Most common encoders don't support more than 2 audio channels:

- MP3 (gst-inspect-1.0 lamemp3enc)

>     Capabilities:
      audio/mpeg
            mpegversion: 1
                  layer: 3
                   rate: { 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000 }
               channels: [ 1, 2 ]


- AAC (gst-inspect-1.0 voaacenc):

>     Capabilities:
      audio/mpeg
            mpegversion: 4
                   rate: { 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 64000, 88200, 96000 }
               channels: [ 1, 2 ]
          stream-format: { adts, raw }
           base-profile: lc

So we are going to change the maximum value from 16 to 2.

**Comment by silviabf** [comment]
Channel parameter only admite now values 1 or 2. I close this issue.
