### ISSUE TITLE
Blurry / fuzzy webcam on first startup of GC 2 beta

### ISSUE THREAD

**Issue by Kirk-LCF** [teltek/Galicaster#381]
On first startup of GC the Webcam (Logitec C270) gives a fuzzy image. Shutdown GC and restart
corrects this. See attached Image.

![bluryy webcam](https://cloud.githubusercontent.com/assets/20046917/17251590/5a839620-55a1-11e6-9e33-15bd6fc55418.png)

**Comment by Alfro** [comment]
@Kirk-LCF We couldn't reproduce this bug. Is it still happening on the current 2.0.x branch?

**Comment by Alfro** [comment]
This issue is 2 years old. I'm closing it, but if this is happening to anyone please feel free to reopen it.
