### ISSUE TITLE
RTP devices / grey video at start of recording.

### ISSUE THREAD

**Issue by Kirk-LCF** [teltek/Galicaster#382]
For the first 2 seconds the recordings are grey. In the screen shot both devices are RTP for Screen and video.

![rtp-grey start](https://cloud.githubusercontent.com/assets/20046917/17251728/d7adf2e4-55a1-11e6-8209-b0a27f58c770.png)

**Comment by smarquard** [comment]
I think they're grey because a keyframe hasn't yet been sent.
