### ISSUE TITLE
Galicaster only record the first 100 scheduled recordings

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#384]
Steps:
- Schedule 300 recordings using the next command to generate an calendar.ical:
python docs/scripts/scheduler.py -l 10 -r 300
- Launch galicaster and left it recording

Problem:
Galicaster only records the first 100 recording, and ignore the next 200.

**Comment by hcaloto** [comment]
Galicaster only reads events (100) when the schedule has changed. So that when having a fixed schedule of 200 recordings, Galicaster will only record the first 100 events.

**Comment by silviabf** [comment]
Galicaster records now more than 100 recordings. I close this issue.

**Comment by silviabf** [comment]
With the last code version, I scheduled 300 recordings but galicaster only recorded 200. I reopen this issue.

**Comment by silviabf** [comment]
fixed, it records until 400 recordings. I close this issue.
