### ISSUE TITLE
Option to record all tracks regardless of capture.device.names

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#388]
In the following scenario, you can end up with recorded tracks being discarded by Galicaster:

1. A venue has a CA (Galicaster, or another) with only a few tracks (e.g. "presenter" such as pyca would reflect).

2. In Opencast, recordings are scheduled for the CA for the future (say 100 recordings over next 3 months).

3. The venue CA is replaced or updated, so there are more tracks available and enable.

4. However, the capture.device.names property in the org.opencastproject.capture.agent.properties still reflects the original set of device names, e.g.:

/usr/share/galicaster-repository# grep capture.device.names */*.properties

5. Galicaster records all configured tracks, but discards the tracks that don't match the capture.device.names list, in this code in galicaster/mediapackage/repository.py:

```
 for bin in bins:
            # TODO rec all and ingest
            capture_dev_names = mp.getOCCaptureAgentProperty('capture.device.names')
            if mp.manual or not capture_dev_names or len(capture_dev_names) == 0 or capture_dev_names == 'defaults' or bin['name'].lower() in capture_dev_names:
                filename = os.path.join(bin['path'], bin['file'])
                dest = os.path.join(mp.getURI(), os.path.basename(filename))
                os.rename(filename, dest)

                etype   = bin['mimetype']
                flavour = bin['flavor'] + '/source'
                mp.add(dest, mediapackage.TYPE_TRACK, flavour, etype, duration) # FIXME MIMETYPE
            else:
                self.logger and self.logger.debug("Not adding {} to MP {}".format(bin['file'],mp.getIdentifier()))
```

As a result, the additional tracks are deleted before ingest (unrecoverable).

A workaround is to set visible_tracks = False so Opencast only ever schedules capture.device.names=defaults, but that's not wanted often because it's helpful to have Opencast show the active tracks on a CA device for other purposes (e.g. monitoring).

So Galicaster should have an option to ignore the capture.device.names property from Opencast, e.g. under [ingest]

ingest_all_tracks = True

**Comment by hcaloto** [comment]
Hi @smarquard,

We will use the name ignore_capture_devices instead of ingest_all_tracks because this piece of code indeed adds the tracks to the mediapackage (and then the ingest is always done with all tracks in the mediapackage)

```
[ingest]
ignore_capture_devices = True
```

**Comment by smarquard** [comment]
Thanks, sounds good.

**Comment by hcaloto** [comment]
Merged (2.0.x)

**Comment by hcaloto** [comment]
Silvia, can you test it?

**Comment by silviabf** [comment]
It is working. With ignore_capture_devices = True, galicaster records all the tracks specified in the profile and it ignores that opencast says. With ignore_capture_devices = False, galicaster only records the tracks that opencast says.
Thanks @smarquard for your suggestion.
