### ISSUE TITLE
Problem with plugin screensaver and "No Audio" window

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#410]
Steps:
- Configure plugin screensaver to 120 seconds
- Launch galicaster with a profile with audio default (using xTag microphone as audio font)
- Leave the microphone muted
- Schedule 10 consecutive recordings separated by one minute (the screensaver will not be appear until the 10 recordings finished)
- Wait

Problem: In the fourth recording the screensaver appears. When you move the mouse, you can see that above galicaster appears galicaster menu bar, as you can see in the attached picture.
![galicaster_01](https://cloud.githubusercontent.com/assets/11191010/17936126/0d4712b0-6a1e-11e6-97d7-2b067b2a81aa.png)

If you do a recording with the same profile of 20 minutes, then the screensaver does not appear.

**Comment by dpeite** [comment]
Can you test the issue in this branch https://github.com/teltek/Galicaster/tree/dev_screensaver

**Comment by silviabf** [comment]
It seems to be fixed. Do the merge and I test it more exhaustive with the rest of QA.

**Comment by silviabf** [comment]
Fixed. I close this issue.
