### ISSUE TITLE
Warning about enable_input not implemented when using rtp bin

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#416]
This warning is logged at start of preview:

 WARNING recorder/base   enable_input not implemented

It seems not to be implemented for rtp.py. If it's not supported by the device, it should be implemented with a method that does nothing, to avoid the unnecessary warning.

You get the warning regardless of whether the muteinput plugin is enabled or not.

**Comment by hcaloto** [comment]
Thanks @smarquard, the message should be printed only if the plugin is enabled

**Comment by smarquard** [comment]
Message no longer appears in logs. Thanks!

**Comment by silviabf** [comment]
Fixed. I close this issue. Thanks smarquard!
