### ISSUE TITLE
Set spatial field in episode.xml for ad-hoc recordings

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#417]
When ad-hoc recordings are ingested to an Opencast server, they lack any info about where the recording came from.

Please add the dcterms:spatial to the episode.xml for ad-hoc recordings, with the capture agent hostname from [ingest] section in the configuration, if set. This should produce an episode.xml like:

```
<?xml version="1.0" encoding="utf-8"?>
<dublincore xmlns="http://www.opencastproject.org/xsd/1.0/dublincore/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/">
   <dcterms:created>2016-09-01T12:50:29Z</dcterms:created>
   <dcterms:identifier>7138ea14-b113-4d6f-854e-6d2914b37de3</dcterms:identifier>
   <dcterms:spatial>whoami</dcterms:spatial>
   <dcterms:title>Recording started at 2016-09-01T14:50:28</dcterms:title>
</dublincore>
```

(where "whoami" is the [ingest] hostname parameter).

Note that Opencast 1.6.x doesn't pay attention to dcterms:spatial (as far as the Admin UI is concerned)l, but Opencast 2.2.x does.

**Comment by smarquard** [comment]
Tested with an Opencast 2.2.x server and this works as expected. Thanks!

**Comment by silviabf** [comment]
Fixed. I close this issue.
