### ISSUE TITLE
Galicaster incorrect recovery from python crash while recording

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#424]
To reproduce:
1. Schedule a recording from Opencast for GC 2.x CA (tested with Opencast 1.6.x server)
2. Galicaster starts recording at the scheduled time
3. While Galicaster is still recording (say after 20s), kill -9 the python process. This simulates the type of crash that one might get with a segfault from an underlying library (say a hardware driver / gstreamer library).
4. Start Galicaster again.

Results:

Galicaster creates a new mediapackage in the repository with "Recovered - title" and the recorded media (until the crash point), but there's an invalid <attachments> section in the manifest.xml which references the original scheduled mediapackage in the repository

```
 <attachment id="org.opencastproject.capture.agent.properties" ref="" type="">
         <mimetype>None</mimetype>
         <url>../gc_snapets4a_20160908T10h54m34/org.opencastproject.capture.agent.properties</url>
         <tags>
            <tag>engage</tag>
         </tags>
      </attachment>
```

Ingest of this mediapackage to the Opencast server fails (because of this invalid attachment).

Expected results:

Galicaster should not create a new mediapackage for the recovered recording, but should instead update the original scheduled mediapackage.

[gc2x-crash-recovery.txt](https://github.com/teltek/Galicaster/files/461222/gc2x-crash-recovery.txt)

**Comment by smarquard** [comment]
Thanks, the commit fixes the problem in our testing.

**Comment by silviabf** [comment]
It is fixed. I close this issue. Thanks @smarquard!.
