### ISSUE TITLE
720p display issues

### ISSUE THREAD

**Issue by ppettit** [teltek/Galicaster#436]
Finally getting to take a look at 2.0 RC1!

On a 720p monitor, I am seeing the main window shifted to the right and down, and everything is too spaced out.

![screenshot of paul-lc2 0 at 2016-10-10 11 47 43](https://cloud.githubusercontent.com/assets/4416453/19235683/1292c1be-8eeb-11e6-8071-53b3c9749f94.png)

It looks like the css styles are the culprit - if i change `min_large = 1200` to `min_large = 1290` ([here](https://github.com/teltek/Galicaster/blob/2.0.x/galicaster/classui/mainwindow.py#L114)) so that `medium` class is added instead of `large` then things look right.
![screenshot of paul-lc2 0 at 2016-10-10 13 20 16](https://cloud.githubusercontent.com/assets/4416453/19235899/53e0dc4a-8eec-11e6-93d9-aaaaba21e320.png)

Don't know if that messes up other resolutions though or if this is something specific to me? If so then I guess this should be configurable?

**Comment by ppettit** [comment]
the above fix no longer works for me (i'm not sure if it ever did now as i can't see how it would have worked!)

doing some more testing. I'm using lilliput touchscreen monitors that have a native 720p resolution, but also tried a dell monitor that has a 1680x1050 resolution.

it only happens if i have a desktop resolution of 720p, no matter what the monitor's native resolution of the monitor is. 

if i set `resolution = 1279x720` or `resolution = 1280x719` in the galicaster config file then it works fine and fills the screen correctly.

weirdly if i start galicaster with 720p resolution so that it displays wrongly, then unplug the monitor and plug it back in while galicaster is still running then it does fill the whole screen correctly once it is plugged back in (but not always). restarting galicaster at that point makes it go wrong again.

i am now thoroughly confused 😕

**Comment by dpeite** [comment]
The problem was the box with the quit button, removing the top margin workaround the problem.

**Comment by ppettit** [comment]
this fixes it for me - thanks!

**Comment by ppettit** [comment]
apologies, i spoke too soon (forgot i had the quit button disabled). for me making sure the sum of the top and bottom margins is 3 or less works. just removing the top margin does not work.

**Comment by Alfro** [comment]
@ppettit No worries.
I have reduced the margin further until I figure out a better way for this to stop happening.

**Comment by silviabf** [comment]
This bug is fixed. I close this issue. Thanks @ppettit !
