### ISSUE TITLE
Set CA state to Error when there's insufficient free disk space

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#438]
If there's not enough free disk space available for Galicaster, it would be preferable for the CA to change its state to error rather than idle (resulting in an Opencast status of unknown being set for the CA).

I have experimented with a plugin to check the available free space:

https://bitbucket.org/cilt/matterhorn_ansible/raw/cc0d3a4d0721f41c3275406f50ac2c73868bd59c/templates/gc2x/checkspace.py

Configure in conf-dist.ini, with

```
[plugins]
checkspace = True
...

[checkspace]
minfreespace=100
checkoninit=true
```

(minfreespace in GB)

but I can't see an easy way for the plugin to change the CA state to error when there's insufficient space (specifically __set_status is a private method).

**Comment by silviabf** [comment]
The plugin works correctly with unscheduled recordings, but if you scheduled a recording and there is no space: the error is delete when the recording begins, the CA records correctly and after the stop the error is shown again.

**Comment by smarquard** [comment]
That sounds like it might be useful: if you have a threshold of say 50G then a scheduled recording could still succeed and it would be better to try than not try at all.

**Comment by Alfro** [comment]
I'm closing this. Considering @smarquard answer to @silviabf comment, it's probably better to leave it as-is, as the QA seemed satisfactory.
