### ISSUE TITLE
Send offline status to Opencast when exiting

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#455]
When Galicaster exits (e.g. through UI), it should update its status on the Opencast server to "offline".

This is a new status added in 2.3.0 in https://opencast.jira.com/browse/MH-11708

This will enable Opencast to show the CA as offline immediately, rather than wait for a timeout period to expire before marking it as offline.

For older Opencast servers, you could either get the server version by calling "/info/components.json" and only send the offline status for servers 2.3.0 or newer, or just send it anyway and ignore any error.

**Comment by silviabf** [comment]
The state offline is sended when you close galicaster. I close this issue. Thanks @smarquard !
