### ISSUE TITLE
Black playback when edit in pause

### ISSUE THREAD

**Issue by dpeite** [teltek/Galicaster#456]
Steps to reproduce:

1. Go to Mediamanager
2. Play any recording
3. Pause the recording
4. Edit metadata

Result:
The playback goes black and until you press play again it's not recover

![image](https://cloud.githubusercontent.com/assets/19955961/21976327/97e53864-dbd1-11e6-9beb-3170fcaeb04a.png)

**Comment by dpeite** [comment]
The error seems to be related to the way the windows are draw in Gtk.

When set off double_buffer property from Gtk.DrawingArea in recorderui.py it works, but add other errors to the GUI.
A workaround for this is enable and disable double_buffer property only when the buttons play and pause are pressed.

**Comment by silviabf** [comment]
There is no black screen now when you edit in pause. This bug is solved and I close this issue.
