### ISSUE TITLE
GTK error when recording title includes ampersand

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#458]
Output to the console (stdout/stderr):

(run_galicaster.py:2009): Gtk-WARNING **: Failed to set text 'Q & A session' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;

This is from the media manager view. Though it appears to display normally.

**Comment by smarquard** [comment]
From the galicaster-repository folder:

org.opencastproject.capture.agent.properties

```
#Capture Agent specific data
#Wed Jan 11 12:02:35 SAST 2017
org.opencastproject.workflow.config.trimHold=true
org.opencastproject.workflow.config.archiveOp=true
org.opencastproject.workflow.definition=full
capture.device.names=presenter,presentation,presentation2,audio
event.series=baa90b35-a67a-4777-92f7-f231df5b91e0
event.title=Q & A session
event.location=ecolt1
org.opencastproject.workflow.config.captionHold=false
```

episode.xml

```
<?xml version="1.0" encoding="utf-8"?>
<dublincore xmlns="http://www.opencastproject.org/xsd/1.0/dublincore/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/">
   <dcterms:license>Creative Commons 3.0: Attribution-NonCommercial-NoDerivs</dcterms:license>
   <dcterms:created>2017-01-16T09:59:59Z</dcterms:created>
   <dcterms:temporal>start=2017-01-16T10:00:00Z; end=2017-01-16T10:55:00Z; scheme=W3C-DTF;</dcterms:temporal>
   <dcterms:creator>ECO1007</dcterms:creator>
   <dcterms:spatial>ecolt1</dcterms:spatial>
   <dcterms:isPartOf>baa90b35-a67a-4777-92f7-f231df5b91e0</dcterms:isPartOf>
   <dcterms:title>Q &amp; A session</dcterms:title>
   <dcterms:identifier>57355620</dcterms:identifier>
</dublincore>
```

**Comment by smarquard** [comment]
I see #300 also includes this. Comment there from @hcaloto:

"Warnings when using the Media Manager (this is due to the tooltip, by disabling these tooltips the issue doesn't happen). See https://bugzilla.gnome.org/show_bug.cgi?id=686843"

**Comment by Alfro** [comment]
@smarquard This should be fixed now.

**Comment by silviabf** [comment]
There is no warning now when you using ampersand. I close this issue. Thanks @smarquard !.
