### ISSUE TITLE
Support additional flavors for multi-stream recording

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#459]
To support scenarios with multiple presentation streams in Galicaster (e.g. audio track, camera track, presentation 1 stream, presentation 2 stream), Galicaster needs to allow flavors beyond "presenter, "presentation", "other".

This is to facilitate processing of such mediapackages by Opencast, where it's currently difficult to construct workflows that have more than one track with the same flavor.

We would like to be able to configure a list of valid flavors to extend the default permitted list. Currently adding "presentation2" as an additional flavor in the following locations worked:

galicaster/recorder/base.py:FLAVOR = ['presenter', 'presentation', 'presentation2', 'other']
galicaster/classui/profile.py:FLAVORS = ["presentation","presentation2","presenter","other"]
galicaster/classui/profile.py:            elif track.flavor == "presentation2":
galicaster/utils/validator.py:FLAVOR = ['presenter', 'presentation', 'presentation2', 'other']

It is not expected that additional flavors like presentation2 would work for side-by-side export from Galicaster, just that they are passed through to Opencast in the manifest.xml unchanged, i.e. as declared in the track definition.

**Comment by Alfro** [comment]
Hi @smarquard 
I have added a configuration parameter called `custom_flavors` that should allow you to add new valid flavors as such:
```
[basic]
...
custom_flavors= presentation2 presentation3
```

This will let the profile validator know that those profiles are also valid and should be allowed.

Please give it a try and let me know if it works for you.

**Comment by smarquard** [comment]
Thanks. What's the commit for this change?

**Comment by Alfro** [comment]
@smarquard I wasn't planning to. From now on, the 2.0.x branch should only include bugfixes that apply to the 2.0 release, and the new features will live only in master until we tag a 2.1.0 release.

**Comment by miesgre** [comment]
@Alfro We want this feature too. When do you plan to release 2.1.0?

**Comment by Alfro** [comment]
@miesgre Pretty soon :) (sorry, I noticed I didn't answer as I was closing these)

This feature has been implemented for the 2.1.0, so I'm closing this issue. Please feel free to reopen it or create a new one should you find any bugs.
