### ISSUE TITLE
The .deb package does not depend explicitly on `gstreamer1.0-pulseaudio`

### ISSUE THREAD

**Issue by sinhote** [teltek/Galicaster#461]
Hi,

I have noted this issue when installing Galicaster in a Lubuntu 16.04. The dependency `gstreamer1.0-pulseaudio` is not installed with the package, and on a closer inspection I've confirmed that it is indeed not listed as a dependency. The issue has probably gone unnoticed so far because (I believe), the package is already installed by default in Ubuntu.

**Comment by Alfro** [comment]
@sinhote Thanks for noticing this.
@dpeite Could you add this dependency to the .deb and test it?

**Comment by dpeite** [comment]
Dependency added in galicaster 2.0.0 package
