### ISSUE TITLE
The default profile in `conf-dist.ini` still has the old caps syntax

### ISSUE THREAD

**Issue by sinhote** [teltek/Galicaster#462]
This does not seem to affect Galicaster --maybe the "caps" variable is ignored, I don't know (in which case I think it should be removed). Anyway, it can be confusing if someone (like myself) reads those pipelines in the `conf-dist.ini` file

**Comment by dpeite** [comment]
You were right, the caps variable was ignored. It's fixed now.

**Comment by silviabf** [comment]
The caps are shown with the new format. I close this issue. Thanks @sinhote!
