### ISSUE TITLE
Use default series for unscheduled recordings

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#468]
If there is a default series specific in the [series] configuration section, that series should be used for Unscheduled recordings. Alternately, it should be possible to specify a series for unscheduled recordings specifically.

It is easier to manage Unscheduled recordings on the Opencast server if they all belong to a series.

**Comment by dpeite** [comment]
Done, now galicaster use `default` parameter (specified in `[series]` section) when a recording is manual and doesn't have any series.

**Comment by smarquard** [comment]
Confirmed that this works correctly (tested in a 2.0.x version with this change cherry-picked)

**Comment by silviabf** [comment]
This works correctly. I close this issue. Thanks @smarquard !
