### ISSUE TITLE
Ability to retrieve series info using authentication

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#469]
The Opencast series retrieval (opencast/series.py) does not use authentication, so only public series are available for selection in Galicaster.

It would be ideal to have an option to enable authentication (using the digest user details) so Galicaster can retrieve non-public series as well.

**Comment by Alfro** [comment]
We changed the request header by mistake in: c9f14670f72acc8fd056295d13e58d603c108ae9
@smarquard It should be fixed now.

**Comment by silviabf** [comment]
The non-public series are shown now. I close this issue. Thanks @smarquard !
