### ISSUE TITLE
Set capture.device.timezone

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#472]
Opencast 2.x complains if the CA timezone is not set correctly, and in cases where the CA is in a different timezone to the core, it seems helpful information to know.

Galicaster should set the CA property:

capture.device.timezone

to the local timezone string as reported by the server (e.g. "Africa/Johannesburg" or "Europe/Madrid")

**Comment by Alfro** [comment]
I don't see a reason not to do it, so I asked my colleague @dpeite to implement this. It should be done very soon!
Thanks @smarquard!

**Comment by Alfro** [comment]
@smarquard Can you confirm if it works now?

**Comment by smarquard** [comment]
Confirmed that capture.device.timezone now shows up in the agent properties, and also <oc:agentTimezone> in the mediapackage XML on the OC server side (mh_scheduled_event).

**Comment by Alfro** [comment]
Awesome, Thanks!
