### ISSUE TITLE
CA in unknown/error state can send status recording

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#473]
If a CA has a scheduled recording for a specific time, but is in an error state (e.g. IP cam unavailable, some device error), it can still post a recording status update for the recording id to Opencast when the start time is reached, even though it's not recording.

Galicaster 2.0.x.

**Comment by Alfro** [comment]
Hi @smarquard, could you give it a try again?

**Comment by androidwiltron** [comment]
hey guys, this raises an error when the recording in manual
```
Traceback (most recent call last):
  File "/home/galicaster/Galicaster/galicaster/opencast/service.py", line 102, in __check_recording_started
    self.t_stop = mp.getDuration()
AttributeError: 'NoneType' object has no attribute 'getDuration'
```

**Comment by dpeite** [comment]
It should be fixed now @androidwiltron

**Comment by smarquard** [comment]
This is now correct in latest 2.0.x code - if the CA is in error state when the scheduled recording time arrives, it sends recording failure update to Opencast for the recording.

**Comment by silviabf** [comment]
This bug is fixed. I close this issue. Thanks @smarquard and @androidwiltron !
