### ISSUE TITLE
Nightly timer doesn't execute at nightly time

### ISSUE THREAD

**Issue by androidwiltron** [teltek/Galicaster#483]
the nightly timer executes every number of seconds until the next nightly timer.
to reproduce:
its 14:00
set `nightly` to 14.02
start galicaster
seconds to nightly is 120s
nightly executes at 14:02
then nightly executes again at 14:04.

```
    def init_timer(self):
        GObject.timeout_add_seconds(self.get_seg_until_next(), self.__notify_timer_daily)

```

this works fine for a set interval, but as this doesnt run again, the timer is stuck at whatever it started as

expected behaviour:
timer waits untill next nightly time (like 24 hours) to execute

**Comment by silviabf** [comment]
Nightly operations are only executed at nightly time now. I close this issue. Thanks @smarquard!
