### ISSUE TITLE
'NoneType' object has no attribute 'set_property'

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#492]
This shows up in our galicaster logs:

```
galicaster	2017-03-29 07:32:39,320	ERROR	recorder/recorder	'NoneType' object has no attribute 'set_property'
```

and in older versions at DEBUG level. Not sure why, but it seems like log clutter.

**Comment by smarquard** [comment]
Profile which causes that error. I think it's associated with the rtp bin.

[basic]
admin = True
repository = /usr/share/galicaster-repository

[logger]
path = /var/log/galicaster/galicaster.log

[ingest]
host = http://media.uct.ac.za
username = matterhorn_system_account
password = digest.0p3nCa5T.matt3rH0rN
hostname = menz9

[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.3

[track2]
name = presenter
device = rtp
flavor = presenter
location = rtspt://menz9-cam01.uct.ac.za/stream
file = presenter.mkv
cameratype = h264
audio = False
muxer = matroskamux
active = True

[track3]
name = presentation
device = v4l2
flavor = presentation
location = /dev/dada0
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
caps-preview = video/x-raw,framerate=1/1
active = True

[track4]
name = presentation2
device = v4l2
flavor = presentation
location = /dev/dada1
file = presentation2.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
caps-preview = video/x-raw,framerate=1/1
active = True

**Comment by smarquard** [comment]
I confirm that this message no longer appears.

**Comment by silviabf** [comment]
This bug is fixed. I close this issue. Thanks @smarquard !
