### ISSUE TITLE
Timeout getting recorder status

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#493]
Seen at UCT and UoM

https://groups.google.com/a/galicaster.org/forum/#!topic/community/VlgXgJpBtxE

ERROR	recorder/recorder	Timeout getting recorder status, current status: (<enum GST_STATE_CHANGE_ASYNC of type Gst.StateChangeReturn>, state=<enum GST_STATE_PAUSED of type Gst.State>, pending=<enum GST_STATE_PLAYING of type Gst.State>) 

It's not reproducible - reboot or restart of Galicaster typically makes it go away.

We've seen it on 6 different CAs.

**Comment by androidwiltron** [comment]
can be reproduced on affected machines by starting and killing gc many times. 1/20 times this may cause the timeout.

i have implemented a workaround that reloads stuff if it times out

https://github.com/UoM-Podcast/Galicaster/commit/74c0e30f5b3d400fa698ac76a72eb1835ed0dfd2
