### ISSUE TITLE
Reword 'timeout' for expected events

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#494]
In the logs, there are entries for start and stop recording times such as:

```
galicaster	2017-03-29 11:59:59,941	INFO	scheduler/scheduler	Timeout to start record 1137774650992909312, duration 3000000 ms
galicaster	2017-03-29 12:49:59,941	INFO	scheduler/scheduler	Timeout to stop record 1137774650992909312
```

"Timeout" most commonly means that the time has run out for something, rather than an expected milestone has been reached. So it would be less ambiguous to word this like:

```
Start time for recording 1137774650992909312, duration 3000000 ms
End time for recording 1137774650992909312
```

and avoids confusion with the other timeout log messages, which are genuine errors.

**Comment by silviabf** [comment]
The log entries are changed. I close this issue. Thanks @smarquard!
