### ISSUE TITLE
Plugin to set CA to error state if audio remains below a threshold

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#495]
In most venues, we have audio input from a DSP with boundary microphones, so there is always audio for the CA.

We would like a plugin to set the CA to error state if the audio remains below a specific threshold for a given period of time. This would indicate an external audio issue, or perhaps a software/OS issue like #387.

Either way, it would allow intervention rather than permitting recordings to proceed with no audio signal.

**Comment by Alfro** [comment]
@smarquard We have added this to the master branch, so it should be available for Galicaster 2.1.0 onwards.
I'll proceed to close this task, but feel free to reopen it if you find any issues (or create a new one).
