### ISSUE TITLE
Allow plugins to process a mediapackage before ingest

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#518]
We have a slow operation (comparing two presentation tracks to see if they are the same, and if so, remove one) that we would like to run for each recording before ingest.

However as the operation can take several minutes, it doesn't seem right to connect it to the recorder-stopped signal, as that delays the UI returning to preview mode.

It seems as if the right thing to do here would be to have an ingest signal, so the plugin can respond to that and process the mediapackage before ingest.

**Comment by Alfro** [comment]
@smarquard Did you try connecting to the "operation-started" signal? This signal is called before a worker operation is executed. Maybe something like...
```python
    from galicaster.core import worker
    def remove_duplicated_presentation(operation_code, mediapackage):
        if operation_code != worker.INGEST_CODE:
            return
        # Here do presentation logic

    dispatcher.connect("operation-started", remove_duplicated_presentation)
```

**Comment by smarquard** [comment]
I'll try that. Is operation-started only used for ingest?

**Comment by Alfro** [comment]
No, it's a generic signal used for every defined worker operation, but the code for operation that is being executed is passed as a parameter so if the operation is a different one it can be ignored.

**Comment by smarquard** [comment]
Right, sorry - didn't read the code snippet properly! That looks perfect then.
