### ISSUE TITLE
An parse error in the calendar can prevent Galicaster from starting

### ISSUE THREAD

**Issue by sinhote** [teltek/Galicaster#525]
Hi,

I reinstalled an agent today and Galicaster would not come up afterwards. Looking up at the logs, this is what got printed:

```
galicaster      2017-05-15 10:07:50,666 WARNING mediapackage/repository Repository folder not specified, using /home/galicaster/Repository`
galicaster      2017-05-15 10:07:50,796 ERROR   galicaster/run_galicaster       Error starting Galicaster: Content line could not be parsed into parts: u';\ufffd\ufffd!\ufffd\ufffd`\ufffdB\ufffd': Key name is required`
```

It was puzzling at first and I did not know where to start to try and solve the problem, but fortunately a few lines above, in the same logs, there were like a thousand messages like the following:

```
galicaster      2017-05-15 09:57:22,817 WARNING mediapackage/repository Repository folder not specified, using /home/galicaster/Repository
galicaster      2017-05-15 09:57:22,947 ERROR   galicaster/run_galicaster       Error starting Galicaster: Content line could not be parsed into parts: u';\ufffd\ufffd!\ufffd\ufffd`\ufffdB\ufffd': Key name is req
uired
galicaster      2017-05-15 09:57:33,043 WARNING mediapackage/repository Repository folder not specified, using /home/galicaster/Repository
galicaster      2017-05-15 09:57:33,176 ERROR   galicaster/run_galicaster       Error starting Galicaster: Content line could not be parsed into parts: u';\ufffd\ufffd!\ufffd\ufffd`\ufffdB\ufffd': Key name is req
uired
galicaster      2017-05-15 09:57:43,341 WARNING mediapackage/repository Repository folder not specified, using /home/galicaster/Repository
galicaster      2017-05-15 09:57:43,473 ERROR   galicaster/run_galicaster       Error starting Galicaster: Content line could not be parsed into parts: u';\ufffd\ufffd!\ufffd\ufffd`\ufffdB\ufffd': Key name is req
uired
```

So, the conclusion here is: the exception does not cause Galicaster to stop or break, but as soon as the app stops, it won't restart again.

I guess the exception is not caught where it should and propagates all the way to `run_galicaster.py`. This one does not look to be too hard to fix, anyway :)

Regards
Rubén

**Comment by Alfro** [comment]
Hi @sinhote, give it a try to the 2.0.x or the master branch. @dpeite has just added a try/catch to the calendar.ical parsing code in case things like this happen.

**Comment by silviabf** [comment]
This bug is fixed. If the calendar has unexpected or corrupted data, galicaster is launched and a new calendar is created. I close this issue.
