### ISSUE TITLE
Replace Scrolled Window for Frame with Buttons

### ISSUE THREAD

**Issue by hectorcanto** [teltek/Galicaster#54]
Due to a bug in GTK, dialogs with scroll bars fail to be modal. Therefore, Scrolledwindow widgets should be replaced for Frames and create the scroll effect with buttons. 

Alternativaly, other scrollbars can be installed.

**Comment by hcaloto** [comment]
Closing the issue, I guess the problem was the profile selector and now it works as a modal window. It was probably solved by updating to GTK 3
