### ISSUE TITLE
Galicaster doesn't start if calendar.ical is empty

### ISSUE THREAD

**Issue by dpeite** [teltek/Galicaster#548]
If calendar.ical it's empty the next error appear and Galicaster not start

`Error starting Galicaster: Found no components where exactly one is required: ''`

**Comment by dpeite** [comment]
Also related with #525

**Comment by Alfro** [comment]
Merged. To QA.

**Comment by silviabf** [comment]
This bug is fixed. If calendar.ical is empty or corrupted, galicaster is launched and a new calendar.ical is created.
