### ISSUE TITLE
 Ingestion before video file is completed

### ISSUE THREAD

**Issue by JamesUoM** [teltek/Galicaster#56]
I'm using the following test profile to record my webcam and 
audiotest and encode them as mp4 and aac.

[data]
name = MyEncode

[track1]
name = WebCam
caps = image/jpeg,framerate=24/1,width=1280,height=720
active = True
location = /dev/video0
file = camera.mp4
device = v4l2
flavor = presenter
videoencoder = videorate ! videoscale add-borders=true ! video/x-raw-yuv,width=320,height=240,framerate=10/1 ! x264enc bitrate=1200 pass=5 quantizer=22
muxer = mp4mux faststart=true

[track2]
amplification = 1.0
name = Noise
vumeter = True
pattern = pink-noise
audioencoder = faac outputformat=1 bitrate=128000
volume = 0.3
player = True
frequency = 440
location = default
file = sound.aac
device = audiotest
flavor = presenter
active = True

The issue I'm seeing it that the zip file ingested by MH contains a truncated version of the camera.mp4 file. If I use faststart the file is actual 0bytes in length, if I don't then it is is a few kbytes shorter. It appears as though galicaster is not waiting for the gstreamer to finish writing the file before zipping and uploading it to MH. MH is then failing at the inspection operation.

Using faststart=true requires the muxer needs to know the size of video track so it can write the headers out first, it does not write anything to the camera.mp4 file until the recording has completed (it does write data to /tmp/qtmux####). This means that if the recording fails you will not have anything on disk to try to salvage (it may not be possible to read the track without a header anyway).

I report this on list with RC2 but still appears to be in 1.3 release

**Comment by hcaloto** [comment]
This issue seems to be solved, It moves the files and perform the ingest operation when all of them are closed

https://github.com/teltek/Galicaster/blob/2.0.x/galicaster/recorder/service.py#L192
