### ISSUE TITLE
Error parsing W3CDTF format with milliseconds from Opencast 4.x

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#566]
OC 4.x includes fractional seconds in the dcterms:created value in episode.xml:

```
<?xml version="1.0" encoding="UTF-8"?><dublincore xmlns="http://www.opencastproject.org/xsd/1.0/dublincore/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:oc="http://www.opencastproject.org/matterhorn/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dcterms:created>2017-12-31T05:00:00.000Z</dcterms:created><dcterms:isPartOf>de1f97d4-381c-4813-b130-1aa51c4c0980</dcterms:isPartOf><dcterms:spatial>somewhere on campus</dcterms:spatial><dcterms:temporal xsi:type="dcterms:Period">start=2017-12-31T05:00:00Z; end=2017-12-31T05:50:00Z; scheme=W3C-DTF;</dcterms:temporal><dcterms:title>mh-12609</dcterms:title><oc:agentTimezone>Africa/Johannesburg</oc:agentTimezone></dublincore>
```

Galicaster doesn't like parsing this:

galicaster	2017-12-14 10:17:19,249	ERROR	utils/queuethread	time data '2017-12-31T05:00:00.000Z' does not match format '%Y-%m-%d %H:%M:%SZ'

**Comment by smarquard** [comment]
Looks like this could originate from marshalDublincore() in "galicaster/mediapackage/mediapackage.py"

```
   if name in ["created"]:
                        creat = _checknget(dom, "dcterms:" + name)
                        if creat:
                            if creat[-1] == "Z":
                                try:
                                    self.setDate(datetime.strptime(creat, "%Y-%m-%dT%H:%M:%SZ"))
                                except:
                                    self.setDate(datetime.strptime(creat, "%Y-%m-%d %H:%M:%SZ"))
                            else:
                                try:
                                    self.setDate(datetime.strptime(creat, "%Y-%m-%dT%H:%M:%S"))
                                except:
                                    self.setDate(datetime.strptime(creat, "%Y-%m-%d %H:%M:%S"))
```

**Comment by smarquard** [comment]
To reproduce this:

* Create an event in Opencast 4.x for a Galicaster CA
* Galicaster retrieves the event. At this point, episode.xml has a created date without the milliseconds
* In the OC 4.x Admin UI, change the event title
* Galicaster updates the event. Now episode.xml has ms in the created timestamp, for example <dcterms:created>2018-01-11T09:00:00.000Z</dcterms:created>
* Galicaster logs error

    galicaster      2018-01-11 10:27:53,760 ERROR   utils/queuethread       time data '2018-01-11T09:00:00.000Z' does not match format '%Y-%m-%d %H:%M:%SZ'

**Comment by Alfro** [comment]
If we are using the manifest.xml "start" property as the **real** date, there may not be any need to parse **dcterm:created** as a datetime, so we wouldn't have to deal with this. #567

**Comment by smarquard** [comment]
Yes, agreed.

**Comment by Alfro** [comment]
I'm closing this as the 'created' field is not converted to 'date' since the changes from #567. It is now left as-is.
