### ISSUE TITLE
Configure delay of Automatic Ingest by a random length of time

### ISSUE THREAD

**Issue by JamesUoM** [teltek/Galicaster#57]
The scenario is a large number of capture agents recording scheduled lectures which all start and finish at the same time. If ingest is set to immediate all the capture agents try to push their files to the ingest server at the same time, resulting in an overloaded server. Yes, load balancing and retrying can mitigate this to some extent but rather than periodically hammering the ingest servers and network, ingest on each capture agent should be configured to occur and some random time in a given duration. eg all capture agent start to ingest in a 15 minute window after the end of a lecture.

**Comment by smarquard** [comment]
James, did you implement this for UoM?

**Comment by JamesUoM** [comment]
Hi,

In the end we didn't. The CA will retry several times and if they fail 
they will ingest at night instead. The time at which they nightly ingest 
we did randomize but this was done using Ansible to set each CA's config 
file individually.

Regards
James

On 07/08/15 11:26, Stephen Marquard wrote:
> James, did you implement this for UoM?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teltek/Galicaster/issues/57#issuecomment-128667975>.
>

-- 
------------------------------------------------------------------------
  James S. Perrin

  Media Technologies Team
  J20, Sackville Building
  The University of Manchester
  Oxford Road, Manchester, M13 9PL

  t: +44 (0) 161 275 6945
  e: james.perrin@manchester.ac.uk
  w: www.manchester.ac.uk/researchcomputing
------------------------------------------------------------------------
"The test of intellect is the refusal to belabour the obvious"
- Alfred Bester
------------------------------------------------------------------------

**Comment by hcaloto** [comment]
I'm going to close this issue, I think the most common use case is ingesting as soon as possible. If not, there is other solutions like James suggests.
