### ISSUE TITLE
Add dcterms:temporal element to episode.xml for ad-hoc recordings

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#570]
Currently for ad-hoc recordings ingested to Opencast 4.x, the duration and end date/time doesn't show up in the Admin UI.

Galicaster could fix this by adding a dcterms:temporal element to the episode.xml file created for ad-hoc recordings, e.g.

````
<dcterms:temporal>start=2018-01-16T14:18:18Z; end=2018-01-16T14:18:34Z; scheme=W3C-DTF;</dcterms:temporal>
````

**Comment by Alfro** [comment]
Done after the changes for #567

**Comment by silviabf** [comment]
In the scheduled recordings, the dterm element is configured as specified:

<dcterms:temporal>start=2018-01-29T15:53:00Z; end=2018-01-29T15:54:00Z; scheme=W3C-DTF;</dcterms:temporal>

but in the manual recordings the parameter has the next format:

<dcterms:temporal>2018-01-29T12:47:36Z</dcterms:temporal>

**Comment by Alfro** [comment]
Sorry, I somehow mistook "temporal" and "created". Now it should be correctly initialized. Also, it should not be changed if it was already added on the ical field.

@smarquard If you could give the master branch a try with an Opencast 4.x to confirm it works? We don't have one Opencast instance with this version at the moment.

**Comment by silviabf** [comment]
Tested with an Opencast 4.x and it works correctly. I close this issue. Thanks @smarquard!
