### ISSUE TITLE
Warning and Error messages in log when you start galicaster

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#576]
Steps:
- Run master branch of galicaster

Problem:
In the galicaster log you can see the next warnings and errors every time you start galicaster:

galicaster    2018-01-26 10:10:41,034    DEBUG    recorder/recorder    Init bin camera galicaster.recorder.bins.v4l2
galicaster    2018-01-26 10:10:41,034    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,034    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,035    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,035    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,036    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,036    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,037    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,037    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,037    DEBUG    recorder/utils    Video sink: sink-camera -> xvimagesink
galicaster    2018-01-26 10:10:41,073    DEBUG    recorder/recorder    Init bin datapath galicaster.recorder.bins.v4l2
galicaster    2018-01-26 10:10:41,073    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,073    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,073    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,073    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,073    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,073    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,073    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,074    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,074    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,075    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,075    DEBUG    recorder/utils    Video sink: sink-datapath -> xvimagesink
galicaster    2018-01-26 10:10:41,106    DEBUG    recorder/recorder    Init bin Revolabs galicaster.recorder.bins.pulse
galicaster    2018-01-26 10:10:41,106    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,106    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,106    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,106    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,106    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,107    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,107    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'
galicaster    2018-01-26 10:10:41,108    ERROR    core/conf    The parameter "custom_flavors" in section "basic" does not exist. Exception: No option 'custom_flavors' in section: 'basic'
galicaster    2018-01-26 10:10:41,108    WARNING    core/conf    There was an error before obtaining a list from the parameter "custom_flavors" in section "basic", FORCED TO "[]". Exception: 'NoneType' object has no attribute 'split'

**Comment by pmgration** [comment]
I've seen this recently too, this came with a new feature in the master branch that is expecting there to be a config option set. I guess when these new features become part of a release the docs will be updated with information about the config options that need to be set (you can set `custom_flavors =` in your basic section to suppress the error messages if you don't need that feature).

**Comment by Alfro** [comment]
My bad. Fix on the way.

**Comment by Alfro** [comment]
I should have added this option's default value to the conf-dist file. Now, since it is correctly set, there should be no message on the logs.

**Comment by silviabf** [comment]
The warnings and errors are not showed more. The bug is fixed. I close the issue.
