### ISSUE TITLE
Wrong configuration of the tags parameter in a profile

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#577]
Testing this new configuration: #575
Steps:
- Configure a tag in a profile:
   tags = engage
- Do a recording with this profile
- See the mediapackage.xml

Problem: As you can see, the tag parameter is not used as a complete word. It is used as if each letter will be a different tag:

> <track id="track-1" type="presentation/source">
         <tags>
            <tag>e</tag>
            <tag>n</tag>
            <tag>g</tag>
            <tag>a</tag>
            <tag>g</tag>
            <tag>e</tag>
         </tags>
         <mimetype>video/avi</mimetype>
         <url>SCREEN.avi</url>
         <duration>9484</duration>
      </track>

I tested also using tags = 'engage' or tags = "engage". The behaviour is the same.

**Comment by Alfro** [comment]
@silviabf That's because the "tags" configuration is an array, so the correct format would be ['engage'].
We should check for type before hand, and either give an error or allow a string as a one element array though, so I'll keep this issue for now.

**Comment by Alfro** [comment]
Okay, it was failing regardless, always taking it as a string. I added the "list" type, so now it should work correctly. Currently the list type for the galicaster validator is using a JSON.loads to parse the conf, so the correct format would be `["engage"]`, with double-quotes. Adding a single string gives an error in the log and the parameter is not loaded (although it is not a profile error, so the profile still records correctly, just without adding the tags)

**Comment by silviabf** [comment]
It works now correctly with the format ["tag"], but If i use a simple string the only error that is in the log is:

> galicaster	2018-01-31 16:37:15,841	DEBUG	recorder/recorder	EOS message successfully received
galicaster	2018-01-31 16:37:16,370	INFO	recorder/service	Adding new mediapackage (6a70f25f-8259-4801-87f6-efa8537619c4) to the repository
galicaster	2018-01-31 16:37:16,371	ERROR	core/conf	The parameter "default" in section "series" does not exist. Exception: No option 'default' in section: 'series'
galicaster	2018-01-31 16:37:16,373	INFO	mediapackage/repository	Repository temporary files removed

And this message in the log seems not related with the tag parameter.

**Comment by Alfro** [comment]
It seems that the bin was ignoring the errors coming from calling parse_validator(). I have added a line that should solve that.

**Comment by silviabf** [comment]
It works correctly now and the error is show in the log when I use a simple string. I close this issue.
