### ISSUE TITLE
Scheduled recordings tracks have tag "archive" when tags parameter is not configured in a profile

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#578]
Testing #575
Steps:
- Use a profile without tags parameter
- Do a scheduled recording

Problem:
If you see the manifest.xml, you can see that all the tracks have "archive" as tag but in the profile does not have tags parameter. In the manual recordings there is no tags in the manifest.xml. If you use a tag parameter in the profile then the manifest.xml have the defined tag.

**Comment by Alfro** [comment]
@silviabf I can't reproduce this, could you attach an ical file that reproduces this behavior?

**Comment by silviabf** [comment]
I can't reproduce it now. I close this issue I'll reopened if it happens again.
