### ISSUE TITLE
Opencast client isn't initialized until short_timer fires for the first time

### ISSUE THREAD

**Issue by pmgration** [teltek/Galicaster#581]
When debugging recently I needed to test ingesting from the `managerui` and noticed that when starting Galicaster it doesn't allow you to ingest until it has established that the Opencast server is available/can be connected to.
Galicaster seems to wait until the first short_timer has fired before [initializing the opencast client](https://github.com/teltek/Galicaster/blob/master/galicaster/opencast/service.py#L157) so there is a period of waiting until recordings can be ingested from the managerui - is there a reason for the delay? Otherwise I might look at getting the client to initialize on start up...

**Comment by dpeite** [comment]
Related to #452

**Comment by pmgration** [comment]
I think this issue has been fixed now by #585 and is part of the 2.1.1 release..?

**Comment by Alfro** [comment]
Yeah, it looks like this was solved when we decided to initialize the Opencast client at start-up with #452

**Comment by Alfro** [comment]
@pmgration I'll tentatively solve it. If you find any issues, don't hesitate to add a comment.
