### ISSUE TITLE
Log warnings about blackmagic profiles

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#582]
Steps:
- Create a profile with a blackmagic card
- Launch galicaster

Problem:
In the log there is these warnings:

> galicaster	2018-02-01 11:01:08,401	WARNING	core/conf	Profile error in /home/galicaster/Galicaster/profiles/blackmagic720p60.ini, profile name: Minidecklink SDI + DVI. INFO: Parameter "subdevice" with value 1 must be a valid option [0, 1, 2, 3], forced to 0. - INFO: Parameter "deinterlace" with value  must be a valid option ['auto', 'interlaced', 'auto-strict'], forced to .
galicaster	2018-02-01 11:01:08,428	WARNING	core/conf	Profile error in /home/galicaster/Galicaster/profiles/datapath.ini, profile name: datapath. INFO: Parameter "subdevice" with value 0 must be a valid option [0, 1, 2, 3], forced to 0. - INFO: Parameter "deinterlace" with value  must be a valid option ['auto', 'interlaced', 'auto-strict'], forced to .
galicaster	2018-02-01 11:01:08,434	WARNING	core/conf	Profile error in /home/galicaster/Galicaster/profiles/blackmagic.ini, profile name: Blackmagic 1080i50 + DVI. INFO: Parameter "input-mode" with value auto must be a valid option ['ntsc', 'ntsc2398', 'pal', 'ntsc-p', 'pal-p', '1080p2398', '1080p24', '1080p25', '1080p2997', '1080p30', '1080i50', '1080i5994', '1080i60', '1080p50', '1080p5994', '1080p60', '720p50', '720p5994', '720p60'], forced to 1080p25. - INFO: Parameter "subdevice" with value 0 must be a valid option [0, 1, 2, 3], forced to 0. - INFO: Parameter "deinterlace" with value  must be a valid option ['auto', 'interlaced', 'auto-strict'], forced to .
galicaster	2018-02-01 11:01:08,439	WARNING	core/conf	Profile error in /home/galicaster/Galicaster/profiles/blackmagic_test.ini, profile name: probando Blackmagic 1080i50 + DVI. INFO: Parameter "subdevice" with value 0 must be a valid option [0, 1, 2, 3], forced to 0. - INFO: Parameter "deinterlace" with value none must be a valid option ['auto', 'interlaced', 'auto-strict'], forced to .
galicaster	2018-02-01 11:01:08,459	WARNING	core/conf	Profile error in /home/galicaster/Galicaster/profiles/blackmagic_xtag.ini, profile name: blackmagic + xtag + DVI. INFO: Parameter "subdevice" with value 0 must be a valid option [0, 1, 2, 3], forced to 0. - INFO: Parameter "deinterlace" with value  must be a valid option ['auto', 'interlaced', 'auto-strict'], forced to .

These warnings doesn't  appear in the 2.0.2 release but they appear in the branch master now.

**Comment by Alfro** [comment]
The subdevice error happens because all profile configuration values are being parsed as a string. I'm taking a better look into it now.

**Comment by Alfro** [comment]
These errors started appearing after the changes from 1013603612bef7ebef52db433c5031da8de47cea. Instead of changing the validator behavior, however, I have opted for correcting the values on the bin itself.

The last commit fixes the `subdevice` and the `deinterlace` warnings.
```
INFO: Parameter "input-mode" with value auto must be a valid option ['ntsc', 'ntsc2398', 'pal', 'ntsc-p', 'pal-p', '1080p2398', '1080p24', '1080p25', '1080p2997', '1080p30', '1080i50', '1080i5994', '1080i60', '1080p50', '1080p5994', '1080p60', '720p50', '720p5994', '720p60'], forced to 1080p25.
```

I can't reproduce the input-mode warning.
```
INFO: Parameter "input-mode" with value auto must be a valid option ['ntsc', 'ntsc2398', 'pal', 'ntsc-p', 'pal-p', '1080p2398', '1080p24', '1080p25', '1080p2997', '1080p30', '1080i50', '1080i5994', '1080i60', '1080p50', '1080p5994', '1080p60', '720p50', '720p5994', '720p60'], forced to 1080p25.
```
@silviabf Please make sure to test this on the master branch, and if it still happens, do attach the profile.ini

**Comment by silviabf** [comment]
There is no more warnings now. I close this issue.
