### ISSUE TITLE
Get Focus on pop up windows and dialogs

### ISSUE THREAD

**Issue by hectorcanto** [teltek/Galicaster#59]
For Windows is easy to do, using gtk.Window.present(), then the focus will be to the first widget on the chain - unless a specific one is set.

For gtk.Dialogs present() won't suit becaurse they are runned (gtk.Dialog.run() blocks and awaits for a response.

**Comment by hcaloto** [comment]
From now on, all pop ups get the focus

https://github.com/teltek/Galicaster/blob/2.0.x/galicaster/classui/message.py#L142
