### ISSUE TITLE
Don't show previous recording details when idle

### ISSUE THREAD

**Issue by pmgration** [teltek/Galicaster#607]
When starting Galicaster the content for the `Recording` tab shows `Not recording`.
As a recording starts the `Not recording` text is replaced with details about the current recording (title and elapsed time).
When the recording stops the title and elapsed time from the previous recording stay on screen until a new recording is made.
This seems to be confusing some of our users (and those at other institutions I've heard)..is there a reason to preserve the information of a previous recording on screen rather than revert back to `Not recording`?

**Comment by androidwiltron** [comment]
Yes I think some may be thinking the same. See a sort of related pr https://github.com/teltek/Galicaster/pull/596

The modification to the behaviour you've mentioned would make sense.
If a list of pervious recordings was something needed it could be done but I think the media manager list would already cover this functionality
