### ISSUE TITLE
Invert Galicaster audio meter on Ubuntu18

### ISSUE THREAD

**Issue by RaiG6** [teltek/Galicaster#618]
On Ubuntu 16, the audio levels are green and mover from left to right:

![Ubuntu16](https://user-images.githubusercontent.com/49396348/59036618-f5513c80-886f-11e9-8ad3-b6fe0baf9db5.JPG)

On Ubuntu 18, the audio levels are orange and move from right to left.

![Ubuntu18](https://user-images.githubusercontent.com/49396348/59036668-069a4900-8870-11e9-847b-80ea2b186827.JPG)

This can be confusing to users. The audio levels should move from left to right as it did in Ubuntu 16.

**Comment by ppettit** [comment]
@RaiG6 been meaning to fix this all year but no users here actually complained so i never got round to it :smile: 

check out the patch in #619 which seems to fix it for me.

**Comment by androidwiltron** [comment]
#619 fixes this should be working in the next galicaster release
