### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by nyok92** [teltek/Galicaster#623]
Hi, is there some news on using galicaster with python 3 (ubuntu 20.04) ?
Thanks a lot

**Comment by q2dg** [comment]
It seems an abandoned project: its main web gives a 504 error

**Comment by silviabf** [comment]
Hello,

Hello, 
Sorry for the delay in the answer. The project continue alive. We are working hard to have a version in python 3 (and Ubuntu 20.04) and we just lauch a release candidate to test: Galicaster Community 3.0.0 - RC2 . You can test it following the next instructions: https://github.com/teltek/Galicaster-doc/blob/master/SoftwareInstallation.md

We hope have the definitive release in the next weeks.

Best regards,
Silvia

**Comment by nyok92** [comment]
Hi, thx for the news ! Wil try it asap.
