### ISSUE TITLE
Use if-modified-since when requesting calendar updates

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#64]
Galicaster always requests the full calendar when polling for updates, whereas the reference Matterhorn CAs support if-modified-since requests. These are more efficient for the server to handle because the server does not need to generate the whole calendar on each request if it hasn't changed recently.

For example the server logs show a request from a reference CA:

[18/Oct/2013:06:41:49 +0200] 137.158.51.163 "GET /recordings/calendars/?agentid=beattie-1 HTTP/1.1" - "-" "Apache-HttpClient/4.0.1 (java 1.5)" 1972 1910 304

with a 304 response code (not modified)

whereas Galicaster requests don't include if-modified-since so always get a 200 response code.

[18/Oct/2013:15:05:56 +0200] 137.158.32.108 "GET /recordings/calendars?agentid=nlc-testCA HTTP/1.1" 111 "-" "Galicaster" 6740 200

With a large number of capture agents, using if-modified-since is more efficient both for server and database resources and bandwidth.

**Comment by rubenrua** [comment]
Cherry pick of UoM-Podcast implementation.

**Comment by genchang1** [comment]
Changes to code  (https://github.com/teltek/Galicaster/commit/6800acac1e9cde7b87681cfdbbad28ed6da4d45b ) caused update of incorrect calender. To correct for this:

In galicaster/utils/mhhttpclient.py 

    - ICAL_ENDPOINT = '/recordings/calendars' 
    + ICAL_ENDPOINT = '/recordings/calendars?agentid={hostname}'

**Comment by rubenrua** [comment]
Thanks @genchang1  for your comment.
