### ISSUE TITLE
Galicaster becomes unstable when the Matterhorn connection is "active" but there's no connection to the internet

### ISSUE THREAD

**Issue by sinhote** [teltek/Galicaster#69]
If a Matterhorn connection is set to "active", but the unit is not connected to a network, Galicaster becomes more unstable and it may freeze or shutdown in the middle of a recording.

**Comment by hcaloto** [comment]
@silviabf, can you check if this still happens?

**Comment by silviabf** [comment]
Yes, this bug continues happening in galicaster 2. But it is not happen if you disconect the network of the CA. To replicate this bug, steps:
- Configure a opencast server in the conf.ini
- connect the CA to internet through a switch
- Launch galicaster
- Start a recording
- Disconnect the network cable in the switch (not the cable that interconnect the CA and the switch)

Problem: The preview of the camera continues correctly, also the recording, but the interface of galicaster is freeze, you can not do nothing until the network is recovered.
In the galicaster log you can see:
```
galicaster	2016-08-24 13:04:23,704	WARNING	opencast/service	Unable t
o connect to opencast server: (28, 'Resolving timed out after 10520 milliseconds
')
galicaster	2016-08-24 13:04:23,705	DEBUG	scheduler/heartbeat	galicast
er-notify-short in 10
galicaster	2016-08-24 13:04:23,706	INFO	opencast/service	Init ope
ncast client
galicaster	2016-08-24 13:04:34,224	WARNING	opencast/service	Unable t
o connect to opencast server: (28, 'Resolving timed out after 10517 milliseconds
')
```

**Comment by silviabf** [comment]
Fixed in galicaster 2. I close this issue. Thanks @sinhote!
