### ISSUE TITLE
audio mimetype is not set correctly when not using mp3

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#78]
We are recording audio in flac format with this config, but the mime-type of the audio track is reported as "audio/mp3" when ingested into Matterhorn.

[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00-CODEC.analog-stereo
file = audio.flac
vumeter = True
amplification = 1.0
active = True
player = True
audioencoder = deinterleave name=d d.src0 ! audioconvert ! flacenc 

Possibly because of this assumption in mediapackage/repository.py:

                etype = 'audio/mp3' if bin['device'] in ['pulse', 'autoaudio', 'audiotest'] else 'video/' + dest.split('.')[1].lower()

Galicaster should set the mime-type correctly, either by having a configurable parameter for it, or by looking at the file extension.

**Comment by hcaloto** [comment]
Already fixed with commit 7af0b5d63b049bde2b21b72d8737a70eb0ddb1d5
