### ISSUE TITLE
Remove old rtpvideo module and make docs consistent

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#81]
It's confusing for adopters to have an rtpvideo and rtp module. It appears as if rtp is newer and more capable (also does audio) so rtpvideo should be removed.

This page:

http://wiki.teltek.es/display/Galicaster/RTP+device+module

includes a reference to "videomux" which is incorrect as the page refers to the rtp module, for which the parameter is "muxer".

Also the references on that page to "rtpvideo" should be replaced with references to "rtp"

**Comment by hcaloto** [comment]
Thanks Stephen.

We won't be removing it for now in the upcoming release, but will update the documentation page so it makes reference to the rtp module instead of the rtpvideo module as it should be deprecated.

**Comment by hcaloto** [comment]
We have already removed rtpvideo (branch 2.0.x) and also the docs do not refer to this device
