### ISSUE TITLE
Device name comparisons should be case-insensitive

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#86]
We lost video from a few recordings because we initially had

[track2]
name = presenter
etc.

then changed to

[track2]
name = Presenter

after we had scheduled recordings on Matterhorn (visible_tracks = True). The recordings then did not record the Presenter track because the item config was for "presenter".

As it seems unlikely that anyone really wants to distinguish between "Presenter" and "presenter" for tracks, Galicaster's device name comparison should be case-insensitive to avoid this type of pitfall.

**Comment by hcaloto** [comment]
With this change this issue should not happen anymore https://github.com/teltek/Galicaster/commit/73da2962fb939324ab908ad64f72a2e35245146b
