### ISSUE TITLE
Blackmagic bin does not free resources correctly after a recording.

### ISSUE THREAD

**Issue by rubenrua** [teltek/Galicaster#99]
See issue #29 and  [Christian Greweling email](http://wiki.teltek.es/display/Galicaster/Community?place=msg%2Fcommunity%2FWf9EDyeeAgw%2FeMnym7_p_BYJ).
It looks like a Gstreamer bug. [2]

[2] https://gist.github.com/rubenrua/dde3276a341494b75115

**Comment by hcaloto** [comment]
This should be worked out once we move to Gstreamer 1.0, so I'm closing this for the moment.
